# flake8: noqa: E501
"""Expected PDF text lines extracted with pypdfium2 for contract PDF tests."""

HASO_CONTRACT_EXPECTED_TEXTS = [
    "Helsinki Haso",
    "Asumisoikeussopimus",
    "1 Sopijapuolet",
    "Talonomistajan nimi",
    "Helsingin Asumisoikeus Oy",
    "Osoite",
    "PL 58226, 00099 Helsingin kaupunki",
    "Puhelin Henkilötunnus tai Y-tunnus",
    "Y-0912770-2",
    "Asumisoikeuden haltijan 1 nimi Asumisoikeuden haltijan 2 nimi",
    "Osoite 1 Osoite 2",
    "Puhelin 1 Puhelin 2",
    "Sähköposti 1 Sähköposti 2",
    "Henkilötunnus 1 Henkilötunnus 2",
    "Asumisoikeuden hyväksyjä Hyväksymispäivämäärä",
    "Järjestysnumero",
    "1",
    "Asta Asukas Bertta Asukas Astankuja 12a5 Bertankaari 8 C 12 040 123 4567 050 987 6543 asta.asukas@esimerkki.fi bertta.asukas@toinen.fi 190395-999X 240900A8883 Helsingin kaupunki 1.7.2020 1234",
    "2 Sopimuksen kohde",
    "Asumisoikeuden haltija saa asumisoikeuden perusteella yksinomaiseen käyttöönsä",
    "seuraavat huonetilat.",
    "Asumisoikeuskohteen nimi",
    "Asumisoikeuskohteen osoite Huoneiston numero",
    "Huoneiston osoite (jos poikkeaa asumisoikeuskohteen osoitteesta)",
    "Huoneistotyyppi (huoneluku) Huoneiston pinta-ala m2 1)",
    "Sijaintikerros",
    "1) Huoneiston pinta-alalla tarkoitetaan sitä asumisoikeuden haltijan yksinomaisessa",
    "käytössä olevaa lattiapinta-alaa, jota rajoittavat huoneistoa ympäröivien seinien",
    "sisäpinnat. Siihen ei kuitenkaan lueta kuuluviksi hormiryhmien, putkikanavien, pilarien,",
    "kantavien seinien, kylmien kuistien, tuulikaappien eikä portaiden vaatimaa alaa portaiden",
    "lähtökerroksessa eikä kellari- ja ullakkotiloja, kahdelle tai useammalle asunnolle yhteisesti",
    "kuuluvaa eteistä, käytävää, WC:tä, pesu- tai kylpyhuonetta, keittiötä tai näihin verrattavaa",
    "muuta yhteiskäyttöön tarkoitettua, asumiseen liittyvää tilaa. Huoneiston pinta-alaa",
    "laskettaessa ei ole otettu lukuun sitä osaa lattiapinta-alasta, jonka kohdalla sisäkaton",
    "korkeus lattiasta on pienempi kuin 160 cm. Huoneiston pinta-alaa yksittäistapauksissa",
    "määrättäessä voidaan muillakin kuin edellä lausutuilla osin käyttää RT-kortiston tai",
    'kiinteistönhoitotiedoston ohjekorttia "Rakennuksen pinta-alat" (SFS 5139-slandardi).',
    "2",
    "Lämmin Koti Oy Lämpimäntie 9 00100 Helsinki C 12 4h+k+s 125.3 77",
    "3 Asumisoikeudesta perittävä asumisoikeusmaksu 2)",
    "3.1 Asumisoikeuden ensimmäinen haltija",
    "Asumisoikeustalon rakentamisvaiheesta perittävä asumisoikeusmaksu",
    "Indeksikorotus Lisä- ja muutostyöt",
    "Asumisoikeusmaksu erääntyy maksettavaksi seuraavan maksuaikataulun mukaisesti",
    "Eränumero Eräpäivämäärä Rakentamisvaihe tai muu",
    "maksuajankohdan peruste",
    "Maksuerän suuruus",
    "1. erä",
    "2. erä",
    "3. erä",
    "Viivästyskorko",
    "Jos maksuerää ei makseta viimeistään eräpäivänä, ostaja on velvollinen maksamaan",
    "viivästyneelle määrälle vuotuista viivästyskorkoa eräpäivästä maksupäivään korkolain",
    "(633/82) 4 §:n 1 momentissa tarkoitetun korkokannan mukaisesti.",
    "2) Kun asumisoikeus perustetaan, oikeuden saajan on maksettava talon omistajalle",
    "asumisoikeusmaksu. Lisäksi asumisoikeuden haltijan on maksettava käyttövastiketta siten",
    "kuin asumisoikeusasunnoista annetussa laissa (393/2021) säädetään. Ehto, jonka mukaan",
    "asumisoikeuden edellytykseksi tai asumisoikeuden perusteella asetetaan asumisoikeuden",
    "haltijalle muu kuin asumisoikeusasunnoista annetussa laissa (393/2021) tarkoitettu",
    "maksuvelvollisuus on mitätön.",
    "3",
    "45 214,00 € 123,45 1200,00",
    "19.8.2020 46 537,45",
    "□",
    "□",
    "3.2 Asumisoikeuden myöhempi haltija",
    "3.2.1. Vastikkeellinen saanto",
    "3.2.1.1. Asumisoikeuden enimmäishinta 3)",
    "Kunnan vahvistama asumisoikeuden enimmäishinta",
    "Kunnan päätös",
    "Asumisoikeusmaksu rakentamisvaiheesta",
    "Tarkistus",
    "erääntynyt",
    "ei erääntynyt",
    "Asumisoikeusmaksulle, sen erääntymisestä tähän päivään saakka",
    "rakennuskustannusindeksin muutoksen mukaan laskettu indeksikorotus 4)",
    "Luovuttajan tai häntä edeltäneiden asumisoikeuden haltijoiden huoneistoon tekemien tai",
    "hallinta-aikanaan rahoittamien kohtuullisten parannusten arvo luovutushetkellä",
    "3) Asumisoikeuden luovutus- tai lunastushinta ei saa ylittää asumisoikeusasunnoista",
    "annetun lain (393/2021) 56 §:n mukaan määräytyvää enimmäishintaa, jonka kunta",
    "vahvistaa. Sitoumus on siltä osin mitätön kuin luovutushinta ylittää sallitun enimmäishinnan.",
    "4) Jos asumisoikeusmaksu suoritetaan erinä, indeksin muutos lasketaan ensimmäisen erän",
    "eräpäivästä.",
    "4",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "3.2.1.2. Asumisoikeudesta sovittu luovutus- tai lunastushinta 5)",
    "Asumisoikeudestaan asumisoikeuden haltija suorittaa",
    "talonomistajalle",
    "luovuttajalle",
    "Luovutushinta",
    "Luovutus on",
    "kokonaan vastikkeellinen",
    "osittain vastikkeellinen",
    "Asumisoikeusmaksun maksaminen",
    "Asumisoikeudesta suoritettavat maksut kuitataan kokonaisuudessaan suoritetuksi",
    "tämän asumisoikeussopimuksen allekirjoituksin.",
    "Asumisoikeudesta suoritettavasta maksusta kuitataan tämän",
    "sopimuksen allekirjoituksin maksetuksi € ja loppuosa erääntyy",
    "maksettavaksi seuraavan maksuaikataulun mukaan.",
    "Asumisoikeusmaksu erääntyy maksettavaksi seuraavan maksuaikataulun mukaan.",
    "(Kts myös kohta 9.1)",
    "Eränumero Eräpäivämäärä Maksuajankohdan peruste Maksuerän suuruus",
    "1. erä",
    "2. erä",
    "3. erä",
    "Viivästyskorko",
    "Erääntyneille maksuille suoritetaan korkolain (633/82) 4 §:n mukaan määräytyvää korkoa.",
    "5",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "Merkitään, että asumisoikeus on edellä mainitun vastikkeen suorittamisen lisäksi saatu",
    "osittain lahjana",
    "perintönä",
    "testamenttina",
    "puolisoiden omaisuuden osituksessa tai erottelussa",
    "yhteisomistussuhteen purkamisessa",
    "Luovuttaja",
    "Luovutus",
    "Luovutusajankohta",
    "5) Asumisoikeudenluovutus- tai lunastushinta ei saa ylittää asumisoikeusasunnoista annetun",
    "lain (393/2021) 56 §:n mukaan määräytyvää enimmäishintaa, jonka kunta vahvistaa.",
    "Sitoumus on siltä osin mitätön kuin luovutushinta ylittää sallitun enimmäishinnan.",
    "3.2.2 Vastikkeeton saanto",
    "Merkitään, että asumisoikeudesta ei ole suoritettu vastiketta ja se on kokonaan saatu",
    "lahjana",
    "perintönä",
    "testamenttina",
    "puolisoiden omaisuuden osituksessa tai erottelussa",
    "yhteisomistussuhteen purkamisessa",
    "Luovuttaja",
    "Luovutus",
    "Luovutusajankohta",
    "6",
    "4 Käyttövastike ja sen suorittaminen 6)",
    "Asumisoikeuden haltijat sitoutuvat maksamaan talonomistajalle käyttövastiketta (arvio",
    "käyttövastikkeesta sisään muuttaessa ks. 9.2 Muut ehdot).",
    "€/kk /m2/kk",
    "Lämmityskustannukset sisältyvät käyttövastikkeeseen",
    "Asumisoikeuden haltijat ovat velvollisia suorittamaan lisäksi seuraavia käyttökorvauksia",
    "Käyttövastikkeen maksupäivä",
    "kuukauden 5. päivä",
    "Pankkitili, jolle käyttövastike maksetaan",
    "isännöitsijä ilmoittaa myöhemmin",
    "Käyttövastikkeen määräytyminen (asumisoikeusasunnoista annetun lain 32 § ja 33 §)",
    "1. Asumisoikeuden haltijalta voidaan periä käyttövastiketta",
    "2. Käyttövastikkeen suuruuden tulee määräytyä niin, että vastiketuloilla voidaan kattaa",
    "yhteisöön kuuluvien asumisoikeusasuntojen ja niihin liittyvien tilojen rahoituksen ja",
    "ylläpidon edellyttämät, kohtuullisen taloudenhoidon mukaiset menot",
    "3. Käyttövastikkeen voidaan sopia määräytyvän niin, että erilaisia menoeriä varten on",
    "eri maksuperuste, kuten huoneiston pinta-alan taikka veden, sähkön tai muun",
    "hyödykkeen todellinen kulutus tai käyttö",
    "4. Käyttövastike ei saa olla paikkakunnalla käyttöarvoltaan samanveroisista",
    "huoneistoista yleensä perittäviä vuokria korkeampi",
    "5. Asuntorahasto voi vahvistaa käyttövastikkeita määrättäessä noudatettavat yleiset",
    "perusteet",
    "Käyttövastikkeen korottaminen (asumisoikeusasunnoista annetun lain 38 §)",
    "1. Milloin talon omistaja haluaa korottaa käyttövastiketta, hänen on ilmoitettava",
    "asumisoikeuden haltijalle siitä kirjallisesti",
    "2. Samalla on ilmoitettava korotuksen peruste ja uusi käyttövastike",
    "3. Korotettu käyttövastike tulee voimaan aikaisintaan kahden kuukauden kuluttua",
    "ilmoituksen tekemistä lähinnä seuraavan käyttövastikkeen maksukauden alusta",
    "4. Erikseen ei kuitenkaan tarvitse ilmoittaa lämmöstä, vedestä tai muusta huoneiston",
    "käyttöön kuuluvasta etuudesta suoritettavasta korvauksen sellaisesta korotuksesta,",
    "joka perustuu kulutuksen kasvuun tai huoneistossa asuvien henkilöiden lukumäärän",
    "7",
    "789,50 € / kk 10,11 € /m²/kk 400 € / kk",
    "□",
    "□",
    "lisääntymiseen, jos etuus on sovittu korvattavaksi erikseen kulutuksen tai",
    "huoneistossa asuvien henkilöiden lukumäärän perusteella",
    "5. Kunkin maksukauden kulutuksen määrä on ilmoitettava asumisoikeuden haltijalle",
    "6) Käyttövastike on maksettava viimeistään toisena päivänä käyttövastikkeen maksukauden",
    "alusta lukien, jollei maksuajasta ole toisin sovittu. Käyttövastikkeen maksukautena pidetään",
    "kuukautta tai muuta ajanjaksoa, jolta käyttövastike sopimuksen mukaan on maksettava.",
    "Ehto, jonka mukaan asumisoikeuden haltijan on suoritettava käyttövastiketta ennakolta, on",
    "mitätön. Kt. asumisoikeusasunnoista annetun lain 32 §, 39 § ja 40 §.",
    "5 Asumisoikeuden kohteena olevien huoneiston ja muiden tilojen",
    "kunto",
    "Huoneisto ja muut tilat luovutetaan siinä kunnossa, missä ne luovutushetkellä ovat",
    "Talonomistaja sitoutuu suorittamaan ilman eri korvausta huoneistossa tai muissa",
    "asumisoikeuden kohteena olevissa tiloissa korjaukset",
    "Mihin mennessä",
    "Mitkä korjaukset",
    "6 Asumisoikeuden kohteena olevien huoneiston ja muiden tilojen",
    "hallinnan luovutus",
    "Asumisoikeuden haltija saa hallintaansa asumisoikeuden kohteena olevan huoneiston ja",
    "muut tilat arviolta (pvm).",
    "Tarkka muuttopäivä ilmoitetaan 3 kuukautta ennen muuttoa. Tarkat muuttoon liittyvät ohjeet",
    "lähetetään n. 6 viikkoa ennen muuttopäivää.",
    "7 Vakuuden asettaminen",
    "Asumisoikeussopimusta tehtäessä tai sopimusehtoja muutettaessa, asumisoikeuden haltijan",
    "vaihtuessa tai näihin verrattavissa tilanteissa voidaan sopia, että asumisoikeuden haltija",
    "8",
    "31.3.2021 — 31.5.2021",
    "□",
    "□",
    "asettaa vakuuden sen vahingon varalta, joka talonomistajalle voi aiheutua siitä, että",
    "asumisoikeuden haltija laiminlyö velvollisuutensa asumisoikeuden haltijana. Jos sovittua",
    "vakuutta ei sovitussa ajassa aseteta, sopimus voidaan purkaa.",
    "Vakuutena asumisoikeuden haltija luovuttaa Helsingin Asumisoikeus Oy haltuun",
    "0,00 € suuruisen rahasumman. Vakuus tulee olla maksettuna avainten luovutukseen",
    "mennessä. Isännöintitoimisto lähettää vastikevakuuslaskut.",
    "8 Asumisoikeuden haltijan osallistuminen asumisoikeustalon",
    "hallintoon ja päätöksen tekoon",
    "Tämän asumisoikeussopimuksen perusteella asumisoikeuden haltija ja hänen kanssaan",
    "asumisoikeusasunnossa asuvat saavat oikeuden osallistua asumisoikeustaloaan",
    "koskevaan hallintoon ja päätöksentekoon vähintään siinä laajuudessa kuin laissa",
    "yhteishallinnosta vuokrataloissa (1169/2022) säädetään.",
    "Asumisoikeuden haltijalla on lisäksi oikeus",
    "Asumisoikeuden haltijalla ja hänen kanssaan asuvalla on lisäksi oikeus",
    "9 Lisäksi on sovittu",
    "9.1 Rakentamisvaiheesta perittävän asumisoikeusmaksun tarkistus",
    "Jos Valtion tukeman asuntorakentamisen keskus Varke tarkistaa hyväksymäänsä",
    "asuntolainoituksen perusteena olevaa hankinta-arvo-osuutta, talonomistaja voi tarkistaa",
    "asumisoikeusmaksua enintään määrällä, joka vastaa asumisoikeusmaksun osuutta",
    "hankinta-arvo-osuuden tarkistuksesta. Asumisoikeusmaksun tarkistusta voi vaatia",
    "maksettavaksi aikaisintaan kahden viikon kuluttua siitä, kun asumisoikeusmaksun",
    "tarkistuksesta ja sen määrästä on kirjallisesti ilmoitettu asumisoikeuden haltijalle.",
    "Asumisoikeusmaksun tarkistuksesta on asumisoikeuden haltijalle ilmoitettava viimeistään",
    "vuoden kuluessa asuntohallituksen tarkistamispäätöksen tekemisestä.",
    "9",
    "Tarkistusta",
    "9.2. Muut ehdot ja sopimuksenteon yhteydessä asiakkaalle luovutetut",
    "asiakirjat",
    "10",
    "Kaikenlaisia ehtoja",
    "Tähän sopimukseen perustuvan asumisoikeuden siirto tai muu luovutus samoin kuin",
    "asumisoikeuden nojalla haltuun saadun koko huoneiston hallinnan luovuttaminen tai",
    "huoneiston hallinnan jakaminen, huoneiston yhteiskäyttö tai sen osan luovuttaminen toiselle",
    "henkilölle määräytyy asumisoikeusasunnoista annetun lain 393/2021 mukaan. Tähän",
    "sopimukseen perustuvan asumisoikeuden pääoma-arvon panttauksesta säädetään edellä",
    "mainitun lain 58 §:ssa.",
    "Jos puolisot käyttävät asumisoikeuden nojalla hallittua huoneistoa yhteisenä asuntonaan, he",
    "vastaavat yhteisvastuullisesti asumisoikeusso pimuksesta johtuvista velvollisuuksista.",
    "Puoliso, joka ei ole asumisoikeussopimuksen osapuoli, vastaa toisen puolison muutettua",
    "huoneis tosta edelleen asumisoikeussopimuksesta johtuvien velvollisuuksien täyttämisestä",
    "niin kauan kuin hän asuu huoneistossa. Puolisoon rinnas tetaan henkilö, jonka kanssa",
    "asumisoikeuden haltija elää avioliiton omaisessa suhteessa. Ks. asumisoikeusasunnoista",
    "annetun 8 §.",
    "Asumisoikeuden lakkaamisesta huoneiston tuhouduttua tai viranomaisen kiellettyä",
    "huoneiston käyttämisen asuntona säädetään asumisoikeusasunnoista annetun lain 29 §.",
    "Tähän sopimukseen perustuva asumisoikeus voi päättyä myös sen johdosta, että",
    "talonomistaja purkaa asumisoikeussopimuksen. Talonomistajan oikeudesta purkaa",
    "asumisoikeussopimus säädetään mainitun lain 68-73§ ja 100 §. Eräissä tapauksissa on",
    "sopimuksen purkamisesta sopimusrikkomuksen johdosta varoitettava ennen kuin sopimus",
    "voidaan purkaa.",
    "Purkamalla sopimus voi päättyä jopa välittömästi. Talon omistajan on annettava",
    "asumisoikeuden haltijalle kirjallinen purkamisilmoitus. Muuttopäivä asumisoikeussopimuksen",
    "päättyessä sopimuksen purkamisen johdosta on sopimuksen päättymispäivää lähinnä",
    "seuraava arkipäivä. Muuttopäivänä asumisoikeuden haltijan on jätettävä puolet huoneistosta",
    "talonomistajan käytettäväksi sekä ennen muuttopäivää lähinnä seuraavan kolmannen",
    "päivän loppua luovutettava huoneisto kokonaan tämän hallintaan.",
    "11",
    "Allekirjoitukset",
    "Tätä sopimusta on tehty kaksi samasanaista kappaletta, toinen talonomistajalle ja toinen",
    "asumisoikeuden haltijalle/haltijoille.",
    "Paikka ja aika",
    "Talonomistaja",
    "Helsingin Asumisoikeus Oy",
    "Valtakirjalla",
    "Asumisoikeuden haltija 1",
    "Asumisoikeuden haltija 2",
    "12",
    "Helsinki 19.8.2020 Maija Myyjä Asta Asukas Bertta Asukas",
]

HITAS_COMPLETE_APARTMENT_CONTRACT_EXPECTED_TEXTS = [
    "1",
    "Valmiin uuden asunnon kauppakirja",
    "1 Sopijapuolet",
    "Myyjän nimi",
    "Helsingin kaupunki / Kaupunkiympäristö, asuntotuotanto",
    "Osoite",
    "PL 58226 / Työpajankatu 8, 00099 Helsingin kaupunki",
    "Henkilötunnus tai Y-tunnus",
    "0201256-6",
    "Ostajan nimi",
    "Omistusosuus osakkeista (ellei omistusosuutta merkitä, oletetaan omistusosuudet yhtä",
    "suuriksi)",
    "Osoite",
    "Puhelin Henkilötunnus tai Y-tunnus",
    "Sähköposti",
    "Matti Meikäläinen 49%Pöhkökatu 1 C 51 040 123 4567 010101-1234 matti.meikalainen@meikä.fi",
    "2",
    "Ostajan nimi",
    "Omistusosuus osakkeista (ellei omistusosuutta merkitä, oletetaan omistusosuudet yhtä",
    "suuriksi)",
    "Osoite",
    "Puhelin Henkilötunnus tai Y-tunnus",
    "Sähköposti",
    "Ostajan nimi",
    "Omistusosuus osakkeista (ellei omistusosuutta merkitä, oletetaan omistusosuudet yhtä",
    "suuriksi)",
    "Osoite",
    "Puhelin Henkilötunnus tai Y-tunnus",
    "Sähköposti",
    "Ostajan nimi",
    "Omistusosuus osakkeista (ellei omistusosuutta merkitä, oletetaan omistusosuudet yhtä",
    "suuriksi)",
    "Osoite",
    "Puhelin Henkilötunnus tai Y-tunnus",
    "Sähköposti",
    "Maija Meikäläinen 51% Möhkälekatu 2 F 64 050 987 6543 020202-2345 maija.meikalainen@meikä.fi",
    "3",
    "2 Kaupan kohde",
    "Yhtiön toiminimi (jäljempänä yhtiö) Y-tunnus",
    "Yhtiön osoite",
    "Kiinteistötunnus Peruste, jolla yhtiö hallitsee",
    "kiinteistöä",
    "Omistus",
    "Vuokra",
    "Osakkaiden numerot Osakkeet oikeuttavat asunnon",
    "nro",
    "hallintaan yhtiön omistamassa",
    "rakennuksessa",
    "Asunnon osoite (jos eri kuin yhtiön osoite)",
    "Asunnon sijaintikerros Huoneistotyyppi (huoneluku) Asuintilojen pinta-ala m²",
    "Muut tilat (ei tarkoita yhtiön hallinnassa olevia tiloja) Muiden tilojen pinta-ala m²",
    "Asunnon käyttöä tai osakkeiden luovutusoikeutta koskevat rajoitukset sekä yhtiöllä,",
    "osakkeenomistajalla tai kunnalla oleva lunastusoikeus",
    "Ei ole",
    "On",
    "Asumiskolo Pöhkö 0912770-2 Mörkötie 12",
    "123-456-789-0",
    "123-456",
    "C 51 Mörkötie 12 C 51 5 4h+k+s+yöpymisparvi 125.3 Muu tila 10.5",
    "Lunastusoikeus lisätiedot",
    "4",
    "3 Kauppahinta ja sen maksaminen",
    "Kauppahinta (kirjaimin ja numeroin)",
    "Myytyihin osakkeisiin kohdistuva osuus yhtiön lainoista",
    "Kauppahinta ja yhtiölainaosuus yhteensä (velaton hinta)",
    "Ostaja on maksanut käsirahan / varausmaksun, joka luetaan osaksi kauppahintaa",
    "Loppukauppahinnan maksuehdot",
    "Kauppahinta on maksettava myyjälle",
    "Pankki ja konttori Tilin numero",
    "Viimeinen erä (valittava suurempi)",
    "Laskusääntö perustuu asuntokauppalain 4 luvun 29 §:ään, jossa on säädetty, kuinka",
    "suuri summa kauppahinnasta on maksettava sulkutilille",
    "0,02 x kauppahinta",
    "0,014 x velaton hinta",
    "euroa on maksettava myyjän lukuun tilille nro",
    "Myyjä saa nostaa tämän summan ja sille mahdollisesti kertyneen talletuskoron pankista",
    "aikaisintaan kuukauden kuluttua siitä, kun asunnon hallinta on luovutettu ostajalle, jollei",
    "ostaja asuntokauppalain 4 luvun 29 §:n mukaan ole oikeutettu kieltämään em. summan",
    "vapauttamista ja kirjallisesti tällä perusteella ennen em. kuukauden määräajan päättymistä",
    "1 234,56 2 345,67 3 580,23 1.1.2024",
    "Loppukauppahinnan maksuehdot ovat seuraavanlaiset...",
    "Testi pankki FI21 1234 5600 0007 85 1 234,56 FI21 1234 5600 0007 87",
    "5",
    "kiellä pankkia luovuttamasta talletusta tai osaa siitä myyjälle. Ostajan on ilmoitettava",
    "kiellosta ja sen perusteista myös myyjälle.",
    "4 Viivästyskorko ja hyvityskorko",
    "Jos maksuerää ei makseta viimeistään eräpäivänä, ostaja on velvollinen maksamaan",
    "viivästyneelle määrälle vuotuista viivästyskorkoa eräpäivästä maksupäivään korkolain",
    "(633/82) 4 §:n 1 momentissa tarkoitetun korkokannan mukaisesti. Maksuerä katsotaan",
    "määräajassa maksetuksi, kun se on maksettu viimeistään eräpäivänä johonkin Suomessa",
    "toimivaan talletuspankkiin edellä kohdassa 3 mainitulle tilille.",
    "Jos maksuerä suoritetaan enemmän kuin 7 päivää ennen sen erääntymistä, ostajalla on",
    "oikeus saada",
    "%/v suuruinen hyvityskorko maksupäivän ja eräpäivän väliseltä ajalta.",
    "5 Osakkeiden omistusoikeus",
    "Osakkeiden omistusoikeus siirtyy ostajalle, kun osakkeiden kauppahinta",
    "kokonaisuudessaan on maksettu.",
    "Osakekirja luovutetaan ostajalle, kun",
    "6 Huoneiston hallinta ja maksuvelvollisuuden alkaminen",
    "Huoneiston hallinta luovutetaan ostajalle",
    "Ostaja vastaa mainitusta ajankohdasta lähtien:",
    "1. Säännöllisistä yhtiövastikkeista ja muista niihin rinnastettavista asuntoyhtiölle",
    "suoritettavista maksuista, jotka kohdistuvat asunnon hallinnan luovutuksen",
    "jälkeiseen aikaan;",
    "2. Muista asunnon hoito-, ylläpito- tai parannuskustannuksista, jotka kohdistuvat",
    "asunnon hallinnan luovutuksen jälkeiseen aikaan, milloin kysymyksessä on",
    "hyödykkeen käyttöön perustuva juokseva meno, tai syntyvät hallinnan luovutuksen",
    "jälkeen, milloin kysymyksessä on muunlainen meno; sekä",
    "3. Asuntoon kohdistuvista julkisoikeudellisista maksuista, joita koskeva",
    "maksuvelvollisuus syntyy asunnon hallinnan luovutuksen jälkeen.",
    "Mikäli hallinnan luovutus viivästyy myyjästä riippuvasta syystä, myyjä on velvollinen",
    "korvaamaan viivästyksestä ostajalle aiheutuneen vahingon asuntokauppalain 4 luvun 11",
    "§:n mukaisesti.",
    "Jos asunnon hallinnan luovutus viivästyy ostajan puolella olevan seikan vuoksi, ostaja",
    "vastaa edellä tarkoitetuista maksuista siitä lähtien, kun hallinnan luovutuksen olisi tämän",
    "kauppasopimuksen mukaan pitänyt tapahtua.",
    "12 12.8.2025 12.8.2025",
    "6",
    "7 Asunnon virhe ja viivästys",
    "Asunnon virhekäsitteestä, vuositarkastuksen ja virheilmoituksen merkityksestä ja virheen",
    "seuraamuksista säädetään asuntokauppalain 4 luvun 14-28 §:issä.",
    "Myyjä järjestää vuositarkastuksen aikaisintaan 12 kuukauden ja viimeistään 15 kuukauden",
    "kuluttua siitä, kun rakennusvalvontaviranomainen on hyväksynyt rakennuksen",
    "käyttöönotettavaksi. Myyjä ilmoittaa vuositarkastuksen ajankohdasta kirjallisesti ostajalle",
    "vähintään kuukautta ennen sen järjestämistä. Ostajan on ilmoitettava vuositarkastuksen",
    "yhteydessä tai viimeistään kolmen viikon kuluessa vuositarkastuksen pöytäkirjan",
    "tiedoksisaannista niistä virheistä, jotka hän on havainnut tai hänen olisi pitänyt havaita",
    "viimeistään vuositarkastuksessa. Muutoin ostaja menettää oikeutensa vedota tällaiseen",
    "virheeseen.",
    "Jos asunnossa ilmenee virhe, jota ostajan ei voida edellyttää havainneen viimeistään",
    "vuositarkastuksessa, hän menettää oikeutensa vedota virheeseen, jollei hän ilmoita",
    "virheestä ja siihen perustuvista vaatimuksistaan kohtuullisessa ajassa siitä, kun hän on",
    "havainnut virheen tai hänen olisi pitänyt se havaita.",
    "Ostaja ei saa virheenä vedota seikkaan, josta hänen täytyy olettaa tienneen kauppaa",
    "tehtäessä. Asunnon ennakkotarkastuksen vaikutuksista sovelletaan, mitä",
    "asuntokauppalain 6 luvun 12 ja 19 §:ssä säädetään.",
    "Ostajalla on asunnon virheen perusteella oikeus pidättyä maksamasta jäljellä olevaa osaa",
    "kauppahinnasta. Ostaja ei kuitenkaan saa pidättää rahamäärää, joka ilmeisesti ylittää ne",
    "vaatimukset, joihin hänellä on virheen perusteella oikeus.",
    "Ostaja voi kohtuullisen ajan kuluessa virheen huomattuaan vaatia virheen korjaamista tai",
    "oikaisemista, mikäli virheen oikaisemisesta aiheutuvat kustannukset eivät ole",
    "kohtuuttoman suuret verrattuna virheen merkitykseen ostajalle. Jos virheen oikaisu ei tule",
    "kysymykseen tai jollei oikaisua suoriteta kohtuullisessa ajassa, ostaja saa vaatia",
    "virheeseen nähden kohtuullista hinnanalennusta tai, jos sopimusrikkomus on olennainen,",
    "purkaa kaupan.",
    "Myyjällä on oikeus, vaikkei ostaja olisi sitä vaatinutkaan, oikaista virhe kohtuullisessa",
    "ajassa kustannuksellaan, ellei siitä aiheudu ostajalle olennaista haittaa, asunnon arvon",
    "alenemista tai vaaraa siitä, että ostajalle aiheutuneet kustannukset jäävät korvaamatta.",
    "Ostajan oikeudesta saada vahingonkorvausta virheen perusteella säädetään",
    "asuntokauppalain 4 luvun 26 §:ssä. Myyjän viivästyksen seuraamuksista säädetään",
    "asuntokauppalain 4 luvun 7-11 §:issä. Ostajan ja yhtiön välisestä puhevallan jaosta",
    "virhetilanteissa säädetään asuntokauppalain 4 luvun 18 a §:ssä.",
    "8 Varainsiirtovero",
    "Tästä osakekaupasta maksettavan varainsiirtoveron suorittaa ostaja. Varainsiirtovero on",
    "maksettava kahden kuukauden kuluessa omistusoikeuden siirtymisestä.",
    "7",
    "9 Ostajan sopimusrikkomukset ja niiden seuraukset",
    "Myyjä saa purkaa kaupan ostajan maksuviivästyksen vuoksi, jos sopimusrikkomus on",
    "olennainen.",
    "Vaihtoehto 1: Myyjällä on oikeus asuntokauppalain 4 luvun 35 §:n 1 momentin",
    "mukaan määräytyvään vahingonkorvaukseen.",
    "Vaihtoehto 2: Ostajan on maksettava myyjälle sopimuksen purkamisesta aiheutuneet",
    "kulut sekä korvauksena myyjälle aiheutuneesta muusta vahingosta 2 % edellä",
    "kohdassa 3. sovitusta velattomasta hinnasta ellei jompikumpi osapuoli erikseen",
    "näytä, että purkamisesta aiheutunut vahinko eroaa siitä olennaisesti. Tällöin ostaja",
    "korvaa aiheutuneen vahingon asuntokauppalain 4 luvun 35 §:n 1 momentin",
    "mukaisesti.",
    "Myyjällä on oikeus edellä mainittuun korvaukseen myös, jos ostaja rikkoo sopimuksen",
    "peruuttamalla kaupan.",
    "Myyjällä ei ole kuitenkaan oikeutta korvaukseen, jos ostajan maksuviivästys tai kaupan",
    "peruuttaminen johtuu lain säännöksestä, yleisen liikenteen tai maksuliikenteen",
    "keskeytyksestä tai muusta samankaltaisesta esteestä, jota ostaja ei kohtuudella voi välttää",
    "eikä voittaa.",
    "Vahingonkorvauksen määrää voidaan sovitella asuntokauppalain 4 luvun 38 §:n",
    "mukaisesti.",
    "10 Menettely kaupan purkautuessa",
    "Jos kauppa puretaan tai ostaja rikkoo sopimuksen peruuttamalla kaupan, myyjän on",
    "palautettava ostajan maksama kauppahinta. Jos ostaja purkaa kaupan myyjän",
    "sopimusrikkomuksen vuoksi, myyjän on tällöin maksettava palautettavalle kauppahinnalle",
    "korkoa korkolain (633/1982) 3 §:n 2 momentissa tarkoitetun korkokannan mukaan siitä",
    "päivästä lukien, jona myyjä vastaanotti maksun. Jos kauppa puretaan sen jälkeen, kun",
    "asunto on luovutettu ostajan hallintaan, ostajan on suoritettava myyjälle kohtuullinen",
    "korvaus asunnosta saamastaan merkittävästä tuotosta tai hyödystä.",
    "Jos ostaja on pannut asuntoon tarpeellisia tai hyödyllisiä kustannuksia, myyjän on kaupan",
    "purkamisen yhteydessä suoritettava niistä ostajalle kohtuullinen korvaus.",
    "Jos asunnon kunto on ostajan hallinta-aikana huonontunut enemmän kuin mitä voidaan",
    "pitää tavanomaisena kulumisena tai jos asunto on tänä aikana vahingoittunut ja tämä",
    "johtuu huolimattomuudesta ostajan puolella, ostaja ei saa purkaa kauppaa, ellei hän",
    "korvaa myyjälle mainitusta syystä johtuvaa arvon alenemista.",
    "8",
    "11 a) Suorituskyvyttömyysvakuus",
    "Myyjä on asettanut yhtiön ja asunto-osakkeen ostajien hyväksi asuntokauppalain 2",
    "luvun 19 §:n mukaisen suorituskyvyttömyysvakuuden:",
    "Merkittävä vakuuden antaja ja vakuuden laji: vakuutus, pankkitakaus tai",
    "Kuluttajaviraston vahvistamat ehdot täyttävä muu takaus. Vakuus on määrältään 25%",
    "yhtiön taloussuunnitelman mukaisista rakennuskustannuksista. Vakuus on voimassa 10",
    "vuotta siitä, kun rakennusvalvontaviranomainen on hyväksynyt rakennuksen",
    "käyttöönotettavaksi.",
    "Liitteenä todistus suorituskyvyttömyysvakuuden asettamisesta.",
    "11 b) Muu vakuus",
    "Jos asunto-osake myydään yhtiöstä, joka on ollut asuntokauppalain 2 luvun mukaisen",
    "rakentamisvaiheen sääntelyn alainen ja rakentamisvaiheen päättymisestä on kulunut",
    "vähemmän kuin yksi vuosi, myyjän on asuntokauppalain 4 luvun 3 §:n mukaan ennen",
    "kaupantekoa asetettava ostajan ja yhtiön hyväksi asuntokauppalain 2 luvun 17 §:n",
    "mukaista vakuutta vastaava vakuus kauppasopimuksen täyttämisestä, mikäli aiemmin",
    "asetetut vakuudet eivät kata myös tätä kauppaa. Vakuus on voimassa 17 §:n mukaisesti,",
    "kuitenkin vähintään kuuden kuukauden ajan siitä, kun asunto on luovutettu ostajan",
    "haltuun.",
    "Ilman ostajien ja yhtiön antamia suostumuksiakin vakuudet vapautuvat viimeistään 12",
    "kuukauden kuluttua yhtiön kaikkien rakennusten vuositarkastuksen pitämisestä, jos yhtiölle",
    "on valittu asuntokauppalain 2 luvun 23 §:ssä tarkoitettu hallitus. Vakuudet eivät kuitenkaan",
    "vapaudu, jos yhtiö tai asunto-osakkeen ostaja vastustaa vakuuksien vapautumista ja",
    "saattaa asian hakemuksella kuluttajavalituslautakunnan tai tuomioistuimen käsiteltäväksi.",
    "Vapautumista vastustavan on ilmoitettava vastustuksestaan sille vakuuden antajalle tai",
    "talletuspankille, joka on vakuudeksi vastaanottanut pankkitalletuksen sekä toimitettava",
    "tälle kuluttajavalituslautakunnan tai käräjäoikeuden antama todistus asian vireille",
    "saattamisesta ennen edellä säädetyn määräajan päättymistä uhalla, että vakuudet muuten",
    "vapautuvat.",
    "Vakuus",
    "Liitteenä asunto-osakeyhtiön antama todistus siitä, että asuntokauppalaissa edelletyt",
    "vakuudet ovat sen hallussa",
    "Liite on",
    "Liitettä ei ole (asuntokauppalain mukaisesta rakentamisvaiheen päättymisestä on",
    "kulunut vuosi tai enemmän)",
    "Kiinteisto kiinnitys",
    "9",
    "12 Rakentamista koskevat säännökset ja määräykset",
    "Yhtiölle on haettu rakennuslupaa",
    "Yhtiö on rakennettu rakennusluvan hakemisajankohtana voimassa olevien säännösten",
    "ja määräysten tai niihin mahdollisesti myönnettyjen poikkeuslupien mukaisesti",
    "13 Erimielisyyksien ratkaiseminen",
    "Jos erimielisyyksiä ei voida ratkaista osapuolten välisellä neuvottelulla, kuluttaja voi",
    "saattaa asian kuluttajavalituslautakunnan käsiteltäväksi kuluttajavalituslautakunnasta",
    "annetun lain (42/1978) mukaisesti.",
    "Jos erimielisyydet saatetaan tuomioistuimen ratkaistaviksi, kanne on nostettava vastaajan",
    "kotipaikan tai asunnon sijaintipaikan yleisessä alioikeudessa. Kuluttajalla on aina oikeus",
    "nostaa kanne Suomessa sijaitsevan asuinpaikkansa yleisessä alioikeudessa.",
    "12.1.2024 Rakennettu säännösten mukaan",
    "10",
    "14 Muut ehdot ja lisätiedot",
    "Muihin ehtoihin merkitään esimerkiksi se, onko huoneisto vuokrattu",
    "Muut sopimusehdot",
    "11",
    "Allekirjoitukset",
    "Tätä kauppakirjaa on tehty kaksi (2) samasanaista allekirjoitettua kappaletta, yksi myyjälle,",
    "yksi ostajalle.",
    "Näiden sopimusehtojen lisäksi kauppaan sovelletaan asuntokauppalakia (843/1994).",
    "Tämän kauppakirjan allekirjoituksella ostaja ilmoittaa tutustuneensa seuraaviin",
    "asiakirjoihin ja vastaanottaneensa ne",
    "Foo.pdf",
    "Bar.pdf",
    "Test.docx",
    "12",
    "Paikka ja aika",
    "Myyjän allekirjoitus",
    "Helsingin kaupunki / Kaupunkiympäristö, asuntotuotanto / Allekirjoitus oikeaksi",
    "todistetaan",
    "Valtakirjalla",
    "Ostajan / ostajien allekirjoitus",
    "Kauppahinta / kauppahinnan loppuerä kuitataan maksetuksi",
    "Paikka ja aika",
    "Myyjän allekirjoitus",
    "Helsingin kaupunki / Kaupunkiympäristö, asuntotuotanto / Allekirjoitus oikeaksi",
    "todistetaan",
    "Valtakirjalla",
    "Osakekirja kuitataan vastaanotetuksi",
    "Paikka ja aika",
    "Ostajan / ostajien allekirjoitus",
    "22.1.2024 Helsinki Markku Myyjä",
    "Matti Meikäläinen",
    "Kuitattu maksetuksi Helsingissä 22.1.2024 Matti Myyjä 22.1.2024",
    "Matti Meikäläinen",
]

HITAS_CONTRACT_EXPECTED_TEXTS = [
    "Helsinki",
    "Asuinhuoneiston rakentamisvaiheen kauppakirja",
    "1 Sopijapuolet",
    "Myyjän nimi",
    "Helsingin kaupunki / Kaupunkiympäristö, asuntotuotanto",
    "Osoite",
    "PL 58226 / Työpajankatu 8, 00099 Helsingin kaupunki",
    "Puhelin Henkilötunnus tai Y-tunnus",
    "0201256-6",
    "Ostajan nimi Ostajan nimi",
    "Omistusosuus osakkeista 1 Omistusosuus osakkeista 1",
    "Osoite Osoite",
    "Puhelin Puhelin",
    "Sähköposti Sähköposti",
    "Henkilötunnus tai Y-tunnus Henkilötunnus tai Y-tunnus",
    "1 Ellei omistusosuutta merkitä, ostajien omistusosuudet oletetaan yhtä suuriksi",
    "1",
    "Matti Meikäläinen Maija Meikäläinen 49% 51% Pöhkökatu 1 C 51 Möhkälekatu 2 F 64 040 123 4567 050 987 6543 matti.meikalainen@meikä.fi maija.meikalainen@meikä.fi 010101-1234 020202-2345",
    "□",
    "□",
    "□",
    "□",
    "□",
    "□",
    "2 Kaupan kohde",
    "Yhtiön toiminimi (jäljempänä yhtiö) Y-tunnus",
    "Yhtiön osoite",
    "Kiinteistötunnus Peruste, jolla yhtiö hallitsee kiinteistöä",
    "omistus",
    "vuokra",
    "Osakkeiden numerot Osakkeet oikeuttavat asunnon",
    "nro hallintaan yhtiön",
    "omistamassa rakennuksessa",
    "Asunnon osoite (jos eri kuin yhtiön osoite)",
    "Asunnon sijaintikerros Huoneistotyyppi (huoneluku) Asuintilojen pinta-ala m2",
    "Muut tilat 2 Muiden tilojen pinta-ala m2",
    "Asunnon käyttöä tai osakkeiden luovutusoikeutta koskevat rajoitukset sekä yhtiöllä,",
    "osakkeenomistajalla tai kunnalla oleva lunastusoikeus",
    "ei ole",
    "on",
    "Ostaja täsmentää valintansa kauppahintaan sisältyvistä asunnon materiaali- tai",
    "varustevaihtoehdoista myöhemmin (rasti ruutuun)",
    "ei",
    "kyllä",
    "Miltä osin",
    "Täsmennyksen ajankohta",
    "Jos ostaja ei tee täsmennystä sovittuna ajankohtana, myyjä täsmentää nämä ominaisuudet",
    "2 Ei tarkoita yhtiön hallinnassa olevia tiloja",
    "2",
    "Asumiskolo Pöhkö 0912770-2 Mörkötie 12",
    "123-456-789-0 123–456",
    "C 51 Mörkötie 12 C 51 5 4h+k+s+yöpymisparvi 125.3 ks. yhtiöjärjestyksen 9-13.",
    "myöhemmin",
    "19.12.2022",
    "□",
    "□",
    "3 Kauppahinta ja sen maksaminen",
    "Kauppahinta (kirjaimin ja numeroin)",
    "Myytyihin osakkeisiin kohdistuva osuus yhtiön lainoista",
    "(Ks. Yhtiöjärjestyksen määräykset lainaosuuden pois maksamisesta)",
    "Kauppahinta ja yhtiölainaosuus yhteensä (velaton hinta)",
    "(Ks kohta 11. Taloussuunnitelman muuttaminen)",
    "Kauppahinta määräytyy maksettavaksi seuraavan aikataulun mukaisesti 3",
    "Eränumero Eräpäivämäärä % €",
    "Toiseksi viim. erä 4",
    "(valittava suurempi)",
    "% €",
    "0,08 x kauppahinta",
    "0,056 x velaton hinta",
    "Eräpäivä ilmoitetaan muuttokirjeessä",
    "3",
    "1 234,56 2 345,67 3 456,78",
    "Maksuerä 1 19.8.2020 12,5 4 567,89 Maksuerä 2 3.9.2020 25,0 5 678,90 Maksuerä 3 3.10.2020 37,5 6 789,01 Maksuerä 4 3.11.2020 50,0 7 890,12 Maksuerä 5 3.12.2020 62,5 8 901,23",
    "9 012,34",
    "6",
    "72,5",
    "□",
    "□",
    "Viimeinen erä 4",
    "(valittava suurempi)",
    "% €",
    "0,02 x kauppahinta",
    "0,014 x velaton hinta",
    "Eräpäivä ilmoitetaan muuttokirjeessä",
    "Kauppahinnasta erät nro (merkitään toiseksi viimeinen erä)",
    "on maksettava myyjän rakennushanketta varten avaamalle pankkitilille",
    "Pankki Tilinumero",
    "Viimeinen kauppahintaerä on maksettava tallettamalla se myyjän tilille",
    "Pankki Tilinumero",
    "Ostajan maksama käsiraha/varausmaksu",
    "sisältyy 1. kauppahintaerään ja ostaja saa vähentää sen 1. kauppahintaerän maksun",
    "yhteydessä",
    "Maksuerien tulee vastata myyjän suorituksen arvoa siten, ettei selvää tai jatkuvaa",
    "suoritusten epätasapainoa ostajan vahingoksi pääse syntymään. Toiseksi viimeinen ja",
    "viimeinen erä saavat kuitenkin erääntyä vasta, kun ostajalla on ollut kohtuullinen tilaisuus",
    "tarkastaa asunto ja asunnon hallinta on ollut luovutettavissa ostajalle.",
    "Jos ostaja aikoo maksaa viimeisen kauppahintaerän ennen sen erääntymistä, tulee hänen",
    "kirjallisesti tiedustella myyjältä, ottaako myyjä suorituksen vastaan. Myyjällä on oikeus",
    "kieltäytyä vastaanottamasta viimeistä erää ennen sen erääntymisajankohtaa.",
    "Myyjä saa nostaa viimeisen kauppahintaerän ja sille mahdollisen kertyneen talletuskoron",
    "pankista aikaisintaan kuukauden kuluttua siitä, kun asunnon hallinta on luovutettu ostajalle,",
    "jollei ostaja asuntokauppalain 4 luvun 29 §:n mukaan ole oikeutettu kieltämään viimeisen",
    "erän vapauttamista ja kirjallisesti tällä perusteella tätä ennen kiellä pankkia luovuttamasta",
    "4",
    "7",
    "82,5 10 123,45 Nordea FI12 3456 7890 1234 56 Nordea FI34 5678 9012 3456 78 1 234,56",
    "talletusta tai osaa siitä myyjälle. Ostajan on ilmoitettava kiellosta ja sen perusteista myös",
    "myyjälle.",
    "3 Jos kauppakirjaan merkitään vain rakennusvaihe, myyjän on ilmoitettava ostajalle",
    "kirjallisesti kunkin rakennusvaiheen valmistumista. Kauppahintaerä erääntyy tällöin",
    "maksettavaksi 14 päivän kuluttua ilmoituksen postin kuljetettavaksi jättämisestä. Jos",
    "kauppakirjaan merkitään eräpäivä ja jos rakennustyö tai työvaihe viivästyy kuukauden tai",
    "enemmän, myyjän on muutettava kauppakirjaan merkittyä eräpäivää viivästystä vastaavasti",
    "ja ilmoitettava ostajalle uusi eräpäivä kirjallisesti heti, kun viivästyksen kesto on myyjän",
    "tiedossa.",
    "4 Laskusääntö perustuu asuntokauppalain 4 luvun 29 §:ään, jonka mukaan toiseksi",
    "viimeinen erä on määrältään vähintään 8 % kauppahinnasta ja viimeinen erä vähintään 2 %",
    "kauppahinnasta. Jos kauppahinta on pienempi kuin 70 % velattomasta hinnasta,",
    "kauppahintana pidetään eriä laskettaessa rahamäärää, joka vastaa 70 % velattomasta",
    "hinnasta. Laskusääntö ei vaikuta kauppahinnan määrään. Se vaikuttaa vain siihen, kuinka",
    "suuri osa kauppahinnasta erääntyy valmistumisvaiheessa.",
    "4 Viivästyskorko ja hyvityskorko",
    "Jos maksuerää ei makseta viimeistään eräpäivänä, ostaja on velvollinen maksamaan",
    "viivästyneelle määrälle vuotuista viivästyskorkoa eräpäivästä maksupäivään korkolain",
    "(633/82) 4 §:n 1 momentissa tarkoitetun korkokannan mukaisesti. Maksuerä katsotaan",
    "määräajassa maksetuksi, kun se on maksettu viimeistään eräpäivänä johonkin Suomessa",
    "toimivaan talletuspankkiin edellä kohdassa 3. mainitulle tilille.",
    "Jos maksuerä suoritetaan enemmän kuin 7 päivää ennen sen erääntymistä, ostajalla on",
    "oikeus saada 0 %/v suuruinen hyvityskorko maksupäivän ja eräpäivän väliseltä ajalta. Katso",
    "kuitenkin mitä kohdissa 3. ja 7. on sanottu viimeisen erän maksamisesta ja omistusoikeuden",
    "siirtymisestä.",
    "5",
    "□",
    "□",
    "□",
    "5 Asunnon arvioitu valmistumisaika (merkitään selvästi kumpi vaihtoehto valitaan)",
    "Vaihtoehto 1 Arvioitu valmistumisaika",
    "Vaihtoehto 2 Asunto valmistuu aikaisintaan ja viimeistään",
    "Myyjän on lähetettävä ostajalle kirjallinen ilmoitus asunnon valmistumispäivästä",
    "viimeistään kuukautta ennen sen valmistumista, jos kauppa on tehty ennen em.",
    "ajankohtaa.",
    "Jäljempänä kohdassa 13. tarkoitettuja myyjän viivästystä koskevia säännöksiä, lukuun",
    "ottamatta ostajan oikeutta pidättyä maksusta, sovelletaan arvioidun valmistumisajan osalta",
    "vasta, mikäli asunnon hallinnan luovutus viivästyy arvioidusta valmistumisajasta enemmän",
    "kuin 30 päivää. Valmistumisajan siirtymisestä myyjän on viipymättä ilmoitettava kirjallisesti",
    "ostajalle.",
    "Vaihtoehto 3 Asunto on valmis. Asunnon hallinta luovutetaan ostajalle",
    "Ostaja vastaa asuntokauppalain 4 luvun 5 §:n mukaisesti hallinnan luovutuksesta lukien",
    "yhtiövastikkeista ja muista asunnosta aiheutuvista kustannuksista.",
    "6 Ennen valmistumista myydyn asunnon hallinnan luovutus ja",
    "vastikkeenmaksuvelvollisuuden alkaminen",
    "Ostaja saa asunnon hallintaansa heti, kun rakennusvalvontaviranomainen on hyväksynyt",
    "sen käyttöönotettavaksi, asunnon vastaanottotarkastus on pidetty, omistusoikeus kaupan",
    "kohteena oleviin osakkeisiin on siirtynyt ja asuntokauppalain 4 luvun 4 §:n mukaisesti",
    "myyjän kanssa sovitut, valmistuneet ja erääntyneet lisä- ja muutostyöt on maksettu.",
    "Edellyttäen, että myyjä on ilmoittanut asunnon hallinnan siirtymispäivästä, ostaja vastaa",
    "asuntokauppalain 4 luvun 5 §:n mukaisesti hallinnan luovutuksesta lukien yhtiövastikkeista ja",
    "muista asunnosta aiheutuvista kustannuksista.",
    "Jos asunnon hallinnan luovutus viivästyy ostajan puolella olevan seikan vuoksi, ostaja",
    "vastaa edellä tarkoitetuista maksuista siitä lähtien, kun hallinnan luovutuksen olisi tämän",
    "kauppasopimuksen mukaan pitänyt tapahtua. Ostajalla ei kuitenkaan ole velvollisuutta ottaa",
    "vastaan asunnon hallintaa aikaisemmin kuin kuukauden kuluttua siitä, kun myyjä lähetti",
    "ilmoituksen hallinnan siirtymispäivästä.",
    "6",
    "31.3.2021 1.4.2021 31.5.2021 30.6.2021",
    "7 Omistusoikeuden siirtyminen ja osakehuoneistorekisteri-ilmoitukset",
    "Omistusoikeus osakkeisiin siirtyy, kun osakkeiden kauppahinta mahdollisine",
    "viivästyskorkoineen on kokonaisuudessaan maksettu. Jos ostaja ilman myyjän suostumusta",
    "maksaa viimeisen kauppahintaerän ennen sen eräpäivää, omistusoikeus siirtyy vasta",
    "viimeisen erän eräpäivänä. Kts. kohta 22 (omistusoikeuden siirtymistä koskeva ehto, jos",
    "ostajalla on aikaisempi Hitas-asunto)",
    "Ennen omistusoikeuden siirtymistä ostajalla on panttioikeus osakkeisiin kauppahintaerien",
    "takaisinmaksamisen sekä mahdollisen koron ja vahingonkorvauksen vakuudeksi. Jos",
    "osakkeet on 10. kohdassa edellytetyin tavoin pantattu, tällä panttioikeudella on parempi",
    "etuoikeus kuin ostajan panttioikeudella.",
    "Turva-asiakirjojen säilyttäjä huolehtii asuntokauppalain mukaisesti tätä osakekauppaa",
    "koskevien ilmoitusten tekemisestä osakehuoneistorekisteriin. Säilyttäjä ei saa ilman myyjän",
    "suostumusta ilmoittaa ostajan saantoa kirjattavaksi osakehuoneistorekisteriin ennen kuin on",
    "selvitetty, että ostaja on maksanut kauppahinnan sekä suorittanut muut siihen rinnastettavat",
    "kauppasopimuksen mukaiset velvoitteet ja asuntokauppalain 2 luvun 6 §:n mukaisesti",
    "myyjän kanssa sovitut, valmistuneet, erääntyneet ja turva-asiakirjan säilyttäjän tiedossa",
    "olevat lisä- ja muutostyöt on maksettu.",
    "Jos kaupan kohteena oleviin osakkeisiin kohdistuu panttioikeus, ulosmittaus tai",
    "turvaamistoimenpide, turva-asiakirjojen säilyttäjä tekee niitä koskevat ilmoitukset",
    "osakehuoneistorekisteriin asuntokauppalain 2 luvun 15 §:ssä tarkoitetun luettelon tietojen",
    "perusteella ostajan saannon kirjaamisen yhteydessä.",
    "8 Varainsiirtovero",
    "Tästä osakekaupasta maksettavan varainsiirtoveron suorittaa ostaja.",
    "Varainsiirtovero on maksettava kahden kuukauden kuluessa omistusoikeuden siirtymisestä",
    "9 Turva-asiakirjat",
    "Talo rakennetaan myyjän ostajalle esittämien ja turva-asiakirjojen säilyttäjälle luovutettujen",
    "turva-asiakirja-asetuksen5 1 §:n mukaisten turva-asiakirjojen ja niiden liitteiden mukaisesti.",
    "Rakentaminen rahoitetaan tähän kauppakirjaan liitetyn taloussuunnitelman mukaisesti",
    "(taloussuunnitelman muuttaminen, ks. kohta 11 ).",
    "7",
    "Turva-asiakirjojen ja osakekirjojen säilyttäjä",
    "Säilytyspaikan osoite, missä turva-asiakirjat ovat ostajan nähtävillä",
    "5 Valtioneuvoston asetus turva-asiakirjoista asuntokaupoissa (835/2005)",
    "10 Kauppakirjaan perustuvien oikeuksien ja velvollisuuksien luovuttaminen ja",
    "panttaaminen",
    "Ostajalla on oikeus, ennen kuin hän on saanut omistusoikeuden osakkeisiin, luovuttaa",
    "kauppasopimuksen tuottamat oikeudet edelleen. Ellei myyjä anna luovutukseen kirjallista",
    "suostumustaan, ostaja vastaa luovutuksesta huolimatta myyjälle tähän kauppakirjaan",
    "perustuvista ostajan velvollisuuksista. Ostajan on välittömästi annettava tieto luovutuksesta",
    "edellä kohdassa 9. mainitulle turva-asiakirjojen säilyttäjälle ja myyjälle luovutussopimuksen",
    "kappaleella tai sen oikeaksi todistetulla jäljennöksellä.",
    "Ostajalla on oikeus ilman myyjän suostumusta pantata tähän kauppakirjaan perustuva",
    "oikeutensa osakkeisiin, asunnon hallintaan ja kaupan ehkä purkautuessa ostajalle",
    "palautettaviin maksuihin.",
    "Ostajan on välittömästi annettava panttauksesta kirjallisesti tieto turva-asiakirjojen",
    "säilyttäjälle.",
    "11 Taloussuunnitelman ja yhtiöjärjestyksen muuttaminen",
    "Yhtiö saa rakentamisvaiheen aikana ottaa velkaa, antaa varallisuuttaan vakuudeksi tai tehdä",
    "muita sitoumuksia vain taloussuunnitelman mukaisesti. Taloussuunnitelmassa ilmoitettua",
    "velkojen määrää voidaan korottaa tai muita vastuita lisätä ainoastaan seuraavissa",
    "tapauksissa:",
    "1. Kaikki ostajat suostuvat kirjallisesti muutokseen.",
    "2. Ilman ostajien suostumusta, jos korotus perustuu",
    "a. lain muutoksesta, viranomaisen päätöksestä tai rakennustyötä kohdanneesta",
    "ennalta arvaamattomasta ja ylivoimaisesta esteestä johtuvaan",
    "rakennuskustannusten nousuun, jonka perusteella yhtiö on rakentamista ja",
    "korjausrakentamista koskevan sopimuksen mukaan velvollinen maksamaan",
    "korotetun hinnan;",
    "8",
    "Ö-Pankki Oyj PL 123, 00020 Ö-Pankki",
    "b. sellaiseen laissa sallittuun rahanarvon muutoksen huomioon ottamiseen,",
    "jonka perusteella yhtiö on rakentamista tai korjausrakentamista koskevan",
    "sopimuksen ehtojen mukaan velvollinen maksamaan korotetun hinnan; tai",
    "c. sellaiseen lain muutoksesta tai viranomaisen päätöksestä johtuvaan yhtiön",
    "muiden velvoitteiden lisäykseen, jota ei ole voitu ottaa huomioon",
    "taloussuunnitelmaa laadittaessa.",
    "3. Ilman ostajien suostumusta voidaan yhtiön menoihin lisätä ostajien omiksi",
    "edustajikseen valitsemien rakennustyön tarkkailijan ja tilintarkastajan palkkiot sekä",
    "muut heidän töistään aiheutuvat kulut, vaikka niitä ei olekaan arvioitu tai mainittu",
    "taloussuunnitelmassa. (Katso kohta 12)",
    "Taloussuunnitelman muutoksesta ja sen perusteesta on viipymättä ilmoitettava turva\x02asiakirjojen säilyttäjälle ja osakkeenostajille. Suostumusta edellyttävässä muutoksessa",
    "ilmoitus on tehtävä ennen taloussuunnitelman muutosta edellyttävään toimenpiteeseen",
    "ryhtymistä.",
    "Taloussuunnitelman muuttaminen ei vaikuta maksettavaan kauppahintaan. Jos yhtiön",
    "velkojen määrää korotetaan, kohdassa 3. sovittu kaupan kohteena oleviin osakkeisiin",
    "kohdistuva lainaosuus nousee kuitenkin vastaavasti.",
    "Yhtiöjärjestystä voidaan muuttaa ilman ostajien ja pantinhaltijan suostumusta vain, jos",
    "muutos ei loukkaa heidän oikeuksiaan ja muuta yhtiön taloudellisen toiminnan perusteita.",
    "12 Osakkeenostajien kokous, tilintarkastajan ja rakennustyön tarkkailijan valinta",
    "Yhtiön hallituksen on kutsuttava osakkeenostajien kokous koolle viivytyksettä sen jälkeen,",
    "kun vähintään yhdestä neljäs-osasta yhtiön asuntoja on tehty luovutussopimus.",
    "Osakkeenostajilla on oikeus yhtiöjärjestyksen estämättä valita yhtiölle tilintarkastaja, jonka",
    "toimikausi kestää sen tilikauden loppuun, jolloin rakentamisvaihe päättyy. Samoin",
    "osakkeenostajilla on oikeus valita rakennustyön tarkkailija, jonka toimikausi kestää",
    "rakentamisvaiheen loppuun. Tarkkailijalla on oltava tehtävän edellyttämä ammattipätevyys",
    "eikä hän saa olla riippuvuussuhteessa rakennustyön suorittajaan tai myyjään.",
    "Tilintarkastajan ja rakennustyön tarkkailijan palkkioista vastaa yhtiö, jonka menoihin palkkiot",
    "sekä muut heidän töistään aiheutuvat kulut saadaan lisätä taloussuunnitelmasta riippumatta.",
    "13 Asunnon luovutuksen viivästyminen",
    "Jos ostajalla on perusteltu syy olettaa, että asunnon hallinnan luovutus tulee viivästymään,",
    "ostajalla on oikeus pidättyä kauppahintaerien maksamisesta, kunnes myyjä saattaa",
    "todennäköiseksi, että hän kykenee täyttämään sopimuksen ajoissa tai että sopimuksen",
    "täyttämisestä asetettu vakuus riittää turvaamaan ostajan oikeudet. Ostajalla on oikeus",
    "9",
    "pidättyä maksusta myyjän viivästyksen vuoksi muissakin asuntokauppalain 4 luvun 7 §:ssä",
    "määritellyissä tilanteissa.",
    "Ostaja saa purkaa kaupan myyjän viivästyksen vuoksi, jos sopimusrikkomus on olennainen.",
    "Asetettamansa kohtuullisen pituisen lisäajan kuluessa ostaja saa purkaa kaupan vain, jos",
    "myyjä ilmoittaa, ettei hän täytä sopimusta tämän ajan kuluessa.",
    "Jos myyjä osoittaa, että viivästys johtuu rakennustyötä kohdanneesta, myyjän ja työhön",
    "osallistuvien urakoitsijoiden sekä näiden käyttämien tavarantoimittajien",
    "vaikutusmahdollisuuksien ulkopuolella olevasta esteestä, jota ei ole kohtuudella voitu ottaa",
    "huomioon kauppaa tehtäessä ja jonka seurauksia ei kohtuudella voida välttää tai voittaa,",
    "ostaja ei saa purkaa kauppaa, ellei viivästyksen kesto ylitä 60 päivää. Mikäli ostaja joutuisi",
    "kohtuuttomaan tilanteeseen, jos hänen olisi pysyttävä sopimuksessa, hän saa kuitenkin",
    "purkaa kaupan edellä olevan estämättä.",
    "Ostaja ei saa purkaa kauppaa myyjän viivästyksen vuoksi sen jälkeen, kun asunto on",
    "luovutettu ostajan hallintaan ja turva-asiakirjojen säilyttäjä on ilmoittanut ostajan saannon",
    "kirjattavaksi osakehuoneistorekisteriin.",
    "Jos ostaja näyttää, että on ennalta painavia syitä olettaa purkuun oikeuttavan viivästyksen",
    "tapahtuvan, ostaja saa purkaa kaupan jo ennen kuin asunnon sovittu luovutusajankohta on",
    "käsillä.",
    "Jos myyjä tiedustelee ostajalta, hyväksyykö tämä viivästyksestä huolimatta määrätyssä",
    "ajassa tapahtuvan sopimuksen täyttämisen eikä ostaja vastaa kohtuullisessa ajassa",
    "tiedustelun saatuaan, ostaja ei saa purkaa kauppaa, jos myyjä täyttää sopimuksen",
    "ilmoittamassaan ajassa.",
    "Ostajalla on oikeus korvaukseen myyjän viivästyksen aiheuttamasta vahingosta",
    "asuntokauppalain 4 luvun 11 §:n mukaisesti.",
    "14 Vuositarkastus, virheilmoitukset ja virheen seuraamukset",
    "Myyjä järjestää vuositarkastuksen aikaisintaan 12 kuukauden ja viimeistään 15 kuukauden",
    "kuluttua siitä, kun rakennusvalvontaviranomainen on hyväksynyt rakennuksen",
    "käyttöönotettavaksi. Myyjä ilmoittaa vuositarkastuksen ajankohdasta kirjallisesti ostajalle",
    "vähintään kuukautta ennen sen järjestämistä. Ostajan on ilmoitettava vuositarkastuksen",
    "yhteydessä tai viimeistään kolmen viikon kuluessa vuositarkastuksen pöytäkirjan",
    "tiedoksisaannista niistä virheistä, jotka hän on havainnut tai hänen olisi pitänyt havaita",
    "viimeistään vuositarkastuksessa. Muutoin ostaja menettää oikeutensa vedota tällaisiin",
    "virheisiin.",
    "Jos asunnossa ilmenee virhe, jota ostajan ei voida edellyttää havainneen viimeistään",
    "vuositarkastuksessa, hän menettää oikeutensa vedota virheeseen, jollei hän ilmoita",
    "10",
    "□",
    "□",
    "virheestä ja siihen perustuvista vaatimuksistaan kohtuullisessa ajassa siitä, kun hän on",
    "havainnut virheen tai hänen olisi pitänyt se havaita.",
    "Ostaja ei saa virheenä vedota seikkaan, josta hänen täytyy olettaa tienneen kauppaa",
    "tehtäessä. Jos asunto sitä myytäessä on valmis, sovelletaan asunnon ennakkotarkastuksen",
    "vaikutuksista, mitä asuntokauppalain 6 luvun 12 ja 19",
    "§:ssä säädetään.",
    "Ostajalla on asunnon virheen perusteella oikeus pidättyä maksamasta jäljellä olevaa osaa",
    "kauppahinnasta. Ostaja ei kuitenkaan saa pidättää rahamäärää, joka ilmeisesti ylittää ne",
    "vaatimukset, joihin hänellä on virheen perusteella oikeus.",
    "Ostaja voi kohtuullisen ajan kuluessa virheen huomattuaan vaatia virheen korjaamista tai",
    "oikaisemista, mikäli virheen oikaisemisesta aiheutuvat kustannukset eivät ole kohtuuttoman",
    "suuret verrattuna virheen merkitykseen ostajalle. Jos virheen oikaisu ei tule kysymykseen tai",
    "jollei oikaisua suoriteta kohtuullisessa ajassa, ostaja saa vaatia virheeseen nähden",
    "kohtuullista hinnanalennusta tai, jos sopimusrikkomus on olennainen, purkaa kaupan.",
    "Myyjällä on oikeus, vaikkei ostaja olisi sitä vaatinutkaan, oikaista virhe kohtuullisessa ajassa",
    "kustannuksellaan, ellei siitä aiheudu ostajalle olennaista haittaa, asunnon arvon alenemista",
    "tai vaaraa siitä, että ostajalle aiheutuneet kustannukset jäävät korvaamatta.",
    "Oikeudesta saada korvausta virheen perusteella säädetään asuntokauppalain 4 luvun 26",
    "§:ssä. Ostajan ja yhtiön välisestä puhevallan jaosta virhetilanteissa säädetään",
    "asuntokauppalain 4 luvun 18 a §:ssä.",
    "15 Ostajan sopimusrikkomukset ja niiden seuraukset",
    "Myyjä saa purkaa kaupan ostajan maksuviivästyksen vuoksi, jos sopimusrikkomus on",
    "olennainen. Jos myyjä tällä perusteella purkaa kaupan (merkittävä kumpi vaihtoehto",
    "valitaan).",
    "Vaihtoehto 1: Myyjällä on oikeus asuntokauppalain 4 luvun 35 §:n 1 momentin mukaan",
    "määräytyvään vahingonkorvaukseen.",
    "Vaihtoehto 2: Ostajan on maksettava myyjälle sopimuksen purkamisesta aiheutuneet",
    "kulut sekä korvauksena myyjälle aiheutuneesta muusta vahingosta 2 % edellä kohdassa 3",
    "sovitusta velattomasta hinnasta, ellei jompikumpi osapuoli erikseen näytä, että purkamisesta",
    "aiheutunut vahinko eroaa siitä olennaisesti. Tällöin ostaja korvaa aiheutuneen vahingon",
    "asuntokauppalain 4 luvun 35 §:n 1 momentin mukaisesti.",
    "Myyjällä on oikeus edellä mainittuun korvaukseen myös, jos ostaja rikkoo sopimuksen",
    "peruuttamalla kaupan.",
    "11",
    "Myyjällä ei ole kuitenkaan oikeutta korvaukseen, jos ostajan maksuviivästys tai kaupan",
    "peruuttaminen johtuu lain säännöksestä, yleisen liikenteen tai maksuliikenteen",
    "keskeytyksestä tai muusta samankaltaisesta esteestä, jota ostaja ei kohtuudella voi välttää",
    "eikä voittaa.",
    "Vahingonkorvauksen määrää voidaan sovitella, jos maksuviivästys tai kaupan",
    "peruuttaminen johtuu maksuvaikeuksista, joihin ostaja on joutunut sairauden, työttömyyden",
    "tai muun erityisen seikan vuoksi pääasiassa omatta syyttään.",
    "16 Menettely kaupan purkautuessa",
    "Jos kauppa puretaan tai ostaja rikkoo sopimuksen peruuttamalla kaupan, myyjän on",
    "palautettava ostajan maksama kauppahinta turva-asiakirjojen säilyttäjälle ostajan ja",
    "mahdollisten pantinhaltijoiden lukuun. Jos kauppa puretaan, myyjän on maksettava",
    "palautettavalle kauppahinnalle korkoa korkolain (633/1982) 3 §:n 2 momentissa tarkoitetun",
    "korkokannan mukaan siitä päivästä lukien, jona myyjä vastaanotti maksun. Jos kauppa",
    "puretaan sen jälkeen, kun asunto on luovutettu ostajan hallintaan, ostajan on suoritettava",
    "myyjälle kohtuullinen korvaus asunnosta saamastaan merkittävästä tuotosta tai hyödystä.",
    "Jos ostaja on pannut asuntoon tarpeellisia tai hyödyllisiä kustannuksia, myyjän on kaupan",
    "purkamisen yhteydessä suoritettava niistä ostajalle kohtuullinen korvaus.",
    "Jos asunnon kunto on ostajan hallinta-aikana huonontunut enemmän kuin mitä voidaan",
    "pitää tavanomaisena kulumisena tai jos asunto on tänä aikana vahingoittunut ja tämä johtuu",
    "huolimattomuudesta ostajan puolelta, ostaja ei saa purkaa kauppaa, ellei hän korvaa",
    "myyjälle mainitusta syystä johtuvaa arvon alenemista.",
    "Myyjän on ilmoitettava kaupan purusta ja peruuttamisesta turva-asiakirjojen säilyttäjälle.",
    "17 Vakuudet",
    "Myyjä on asettanut ja luovuttanut turva-asiakirjojen säilyttäjälle yhtiön ja asunto\x02osakkeenostajien hyväksi seuraavat vakuudet.",
    "A) Asuntokauppalain 2 luvun 17 §:n mukainen rakentamisvaiheen vakuus",
    "12",
    "kiinteistökiinnitys",
    "Merkittävä vakuuden laji: pankkitalletus, pankkitakaus tai tarkoitukseen soveltuva",
    "vakuutus, joka on määrältään aluksi vähintään 5 % yhtiön taloussuunnitelmaan merkityistä",
    "rakennuskustannuksista ja kulloinkin vähintään 10 % myytyjen asunto-osakkeiden",
    "kauppahintojen yhteismäärästä. Vakuuden on oltava voimassa vähintään 3 kuukautta",
    "siitä, kun rakennusvalvontaviranomainen on hyväksynyt rakennuksen käyttöönotettavaksi.",
    "Rakentamisvaiheen vakuuden lakatessa, myyjä asettaa tilalle rakentamisvaiheen",
    "jälkeisen vakuuden, joka on määrältään vähintään 2 % myytyjen osakkeiden",
    "kauppahintojen yhteismäärästä. Tämä vakuus on voimassa vähintään 15 kuukautta sen",
    "jälkeen, kun rakennusvalvontaviranomainen on hyväksynyt rakennuksen",
    "käyttöönotettavaksi. Rakentamisvaiheen jälkeisen vakuuden asettamisvelvollisuus lakkaa,",
    "kun on kulunut 15 kuukautta rakennuksen käyttöönottohyväksynnästä. Jos asunto\x02osakkeiden kauppahinta on vähemmän kuin 70 % velattomasta hinnasta, kauppahintana",
    "rakentamisvaiheen ja rakentamisvaiheen jälkeistä vakuutta laskettaessa pidetään",
    "rahamäärää, joka vastaa 70 % myytyjen osakkeiden velattomasta hinnasta.",
    "Yhtiön ja osakkeenostajien on annettava kirjallinen suostumus vakuuksien",
    "vapauttamiselle, kun perustajaosakas on täyttänyt rakentamista koskevan sopimuksen ja",
    "asunto-osakkeiden kauppaa koskevien sopimusten mukaiset velvoitteensa. Yhtiö tai",
    "osakkeenostaja, joka aiheettomasti ja vastoin kuluttajariitalautakunnan6 suositusta on",
    "kieltäytynyt antamasta suostumusta vakuuden vapauttamiseen, voidaan velvoittaa",
    "korvaamaan tästä myyjälle aiheutunut vahinko kohtuullisella määrällä.",
    "liman ostajien ja yhtiön antamia suostumuksiakin vakuudet vapautuvat viimeistään 12",
    "kuukauden kuluttua yhtiön kaikkien rakennusten vuositarkastuksen pitämisestä, jos",
    "yhtiölle on valittu asuntokauppalain 2 luvun 23 §:ssä tarkoitettu hallitus. Vakuudet eivät",
    "kuitenkaan vapaudu, jos yhtiö tai asunto-osakkeen ostaja vastustaa vakuuksien",
    "vapautumista ja saattaa asian hakemuksella kuluttajavalituslautakunnan tai",
    "tuomioistuimen käsiteltäväksi. Vapautumista vastustavan on ilmoitettava vastustuksestaan",
    "sille vakuuden antajalle tai talletuspankille, joka on vakuudeksi vastaanottanut",
    "pankkitalletuksen sekä toimitettava tälle kuluttajavalituslautakunnan tai käräjäoikeuden",
    "antama todistus asian vireille saattamisesta ennen edellä säädetyn määräajan",
    "päättymistä uhalla, että vakuudet muuten vapautuvat.",
    "Merkitään vakuuden antaja tai se talletuspankki, joka on vakuudeksi vastaanottanut",
    "pankkitalletuksen ja jolle tässä kappaleessa tarkoitettu ilmoitus ja todistus on toimitettava.",
    "B) Asuntokauppalain 2 luvun 19 §:n mukainen suorituskyvyttömyysvakuus",
    "13",
    "pankkitalletus 100 € Ä-Pankki Oyj:ssä",
    "Merkittävä vakuuden antaja ja vakuuden laji: vakuutus, pankkitakaus tai Kuluttajaviraston",
    "vahvistamat ehdot täyttävä muu takaus. Vakuus on määrältään 25 % yhtiön",
    "taloussuunnitelman mukaisista rakennuskustannuksista. Vakuus on voimassa 10 vuotta",
    "siitä, kun rakennusvalvontaviranomainen on hyväksynyt rakennuksen käyttöönotettavaksi",
    "6 Kuluttajariitalautakunnasta annetun lain (42/1978) 1 §:n mukaan kuluttajariitalautakunta voi",
    "antaa ratkaisusuosituksia vakuuden käyttöä ja sen vapauttamista koskevissa yksittäisissä",
    "riita-asioissa riippumatta siitä, kuka riidan osapuolista saattaa asian lautakunnan",
    "käsiteltäväksi.",
    "18 Myyjän ilmoitusten tiedoksisaanti",
    "Myyjän ostajalle lähettämän kirjallisen ilmoituksen on katsottava saapuneen ostajalle",
    "viimeistään seitsemäntenä päivänä lähettämisen jälkeen, jos se on lähetetty ostajan myyjälle",
    "viimeksi ilmoittamaan osoitteeseen.",
    "19 Rakentamista koskevat säännökset ja määräykset",
    "Yhtiölle on haettu rakennuslupaa",
    "Yhtiö rakennetaan rakennusluvan hakemisajankohtana voimassa olevien säännösten ja",
    "määräysten tai niihin mahdollisesti myönnettyjen poikkeuslupien mukaisesti.",
    "20 Mikäli laite- tai materiaalitoimittaja on antanut asuntoon kuuluvaan laitteeseen tai",
    "materiaaliin takuun, myyjä ei vastaa tästä takuusta",
    "21 Erimielisyyksien ratkaiseminen",
    "Jos erimielisyyksiä ei voida ratkaista osapuolten välisellä neuvottelulla, asia voidaan saattaa",
    "kuluttajariitalautakunnan käsiteltäväksi kuluttajariitalautakunnasta annetun lain mukaisesti.",
    "Jos erimielisyydet saatetaan tuomioistuimen ratkaistavaksi, kanne on nostettava vastaajan",
    "kotipaikkakunnan tai asunnon sijaintipaikkakunnan yleisessä alioikeudessa. Kuluttaja voi",
    "nostaa kanteen myös Suomessa sijaitsevan asuinpaikkansa yleisessä alioikeudessa.",
    "22 Muut ehdot",
    "Hitas-ehtojen mukaisesti ostaja/ostajatalous ei saa pysyvästi omistaa muita Hitas-asunto\x02osakkeita. (ks. erillinen kauppakirjan Hitas-omistusliite)",
    "Omistusoikeus kaupan kohteena oleviin osakkeisiin siirtyy ostajalle, kun kauppahinta on",
    "kokonaisuudessaan maksettu ja kun aikaisemmat Hitas-osakkeet on luovutettu",
    "14",
    "1.7.2020",
    "omistusoikeudella. Ostaja on velvollinen esittämään luovutuksista selvityksen myyjälle",
    "asunnon valmistumiseen mennessä.",
    "Myyjällä on oikeus purkaa kauppa, mikäli aikaisempia Hitas-osakkeita ei ole luovutettu",
    "omistusoikeudella ennen kaupan kohteena olevan asunnon valmistumista. Myyjällä on",
    "oikeus omistamisrajoituksen rikkomistilanteissa purkaa kauppa kohtuullisen ajan kuluessa",
    "kuitenkin viimeistään kuuden (6) kuukauden kuluessa kaupan kohteena olevan asunnon",
    "valmistumisesta.",
    "Erityisistä syistä Asuntopalvelut voi myöntää ostajalle lisäaikaa aikaisemman asunnon",
    "luovuttamiselle, jolloin myyjän oikeus purkaa kauppa siirtyy vastaavasti.",
    "Muut ehdot",
    "15",
    "Muita ehtoja ja myös sellasta",
    "Muut ehdot jatkuu",
    "Ostajan vakuutus ja kaupanteon yhteydessä luovutetut asiakirjat",
    "Ostajalle on esitetty kauppakirjan kohdassa 9. tarkoitetut turva-asiakirjat. Tämän",
    "kauppakirjan allekirjoituksella ostaja vakuuttaa huolellisesti tutustuneensa turva-asiakirjoihin",
    "sekä ilmoittaa hyväksyvänsä tämän kaupan ehdot.",
    "Näiden sopimusehtojen lisäksi kauppaan sovelletaan asuntokauppalakia (843/1994) ja",
    "valtioneuvoston asetusta turva-asiakirjoista asuntokaupoissa (835/2005).",
    "16",
    "Tämän asiakirjan allekirjoituksella ostaja kuittaa samalla vastaanottaneensa seuraavat",
    "kaupanteon yhteydessä luovutetut asiakirjat:",
    "17",
    "ehkä",
    "Allekirjoitukset",
    "Tätä kauppakirjaa on tehty kolme samasanaista kappaletta, yksi kummallekin sopijapuolelle",
    "ja yksi turva-asiakirjojen säilyttäjälle. Myyjä toimittaa välittömästi kauppakirjakappaleen",
    "turva-asiakirjojen säilyttäjälle.",
    "Paikka ja aika",
    "Myyjä",
    "Helsingin kaupunki/ Kaupunkiympäristö, asuntotuotanto / Allekirjoitus oikeaksi todistetaan",
    "Valtakirjalla",
    "Ostaja/ostajat",
    "Asuntokauppalain edellyttämät vakuudet on asetettu kohdan 17. mukaisesti",
    "Paikka ja aika",
    "Turva-asiakirjojen säilyttäjä",
    "18",
    "Mörkökylässä 1.7.2020",
    "Mörkö",
    "Matti Meikäläinen & Maija Meikäläinen",
    "Ö-Pankki Oyj, PL 123, 00020 Ö-Pankki",
]
