# Generated by Django 3.2.11 on 2022-02-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0045_populate_application_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="profile",
        ),
    ]
