# Generated by Django 2.2.20 on 2021-04-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MappedApartment",
            fields=[
                ("apartment_uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("mapped_etuovi", models.BooleanField(null=True)),
                ("mapped_oikotie", models.BooleanField(null=True)),
            ],
        ),
    ]
