# Generated by Django 4.2.11 on 2026-01-22 13:31

from django.db import migrations, models


def set_last_mapped_to_fields(apps, schema_editor):
    MappedApartment = apps.get_model("connections", "MappedApartment")
    # Set last_mapped_to_etuovi where needed
    from django.db.models import Case, DateTimeField, F, When

    # Use the later of created_at or updated_at for last_mapped_to_etuovi
    MappedApartment.objects.filter(mapped_etuovi=True).update(
        last_mapped_to_etuovi=Case(
            When(
                updated_at__gt=F("created_at"),
                then=F("updated_at"),
            ),
            default=F("created_at"),
            output_field=DateTimeField(),
        )
    )

    # Use the later of created_at or updated_at for last_mapped_to_oikotie
    MappedApartment.objects.filter(mapped_oikotie=True).update(
        last_mapped_to_oikotie=Case(
            When(
                updated_at__gt=F("created_at"),
                then=F("updated_at"),
            ),
            default=F("created_at"),
            output_field=DateTimeField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_add_timestamp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappedapartment",
            name="last_mapped_to_etuovi",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mappedapartment",
            name="last_mapped_to_oikotie",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            set_last_mapped_to_fields, reverse_code=migrations.RunPython.noop
        ),
    ]

    from django.db import migrations
