# Generated by Django 2.2.21 on 2021-05-07 05:36

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="last name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="phone number"),
                ),
                (
                    "bank_account",
                    models.CharField(max_length=30, verbose_name="bank account number"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="address")),
                (
                    "ssn",
                    models.CharField(
                        max_length=11, verbose_name="personal identification number"
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="city")),
                (
                    "postal_code",
                    models.CharField(max_length=5, verbose_name="postal code"),
                ),
                (
                    "right_of_residence",
                    models.CharField(
                        max_length=10, verbose_name="right of residence number"
                    ),
                ),
                (
                    "contact_language",
                    models.CharField(
                        choices=[
                            ("fi", "Finnish"),
                            ("sv", "Swedish"),
                            ("en", "English"),
                        ],
                        max_length=2,
                        verbose_name="contact language",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("is_staff", models.BooleanField(default=False, verbose_name="staff")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
