# Generated by Django 2.2.21 on 2021-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=40, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="postal code"),
        ),
    ]
