# Generated by Django 2.2.21 on 2021-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_timestamp_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="street_address",
            field=models.CharField(
                default="", max_length=200, verbose_name="street address"
            ),
            preserve_default=False,
        ),
    ]
