# Generated by Django 2.2.24 on 2021-06-17 10:41

import pgcrypto.fields
from django.db import migrations

import apartment_application_service.fields


def copy_values(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all().iterator():
        profile.encrypted_city = profile.city
        profile.encrypted_contact_language = profile.contact_language
        profile.encrypted_date_of_birth = profile.date_of_birth
        profile.encrypted_id = profile.id
        profile.encrypted_phone_number = profile.phone_number
        profile.encrypted_postal_code = profile.postal_code
        profile.encrypted_street_address = profile.street_address
        profile.encrypted_first_name = profile.user.first_name
        profile.encrypted_last_name = profile.user.last_name
        profile.encrypted_email = profile.user.email
        profile.save()
        profile.user.first_name = ""
        profile.user.last_name = ""
        profile.user.email = ""
        profile.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_profile_right_of_residence"),
        ("pgcrypto", "0001_add_pgcrypto_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="encrypted_city",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True, max_length=50, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_contact_language",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True,
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=2,
                verbose_name="contact language",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_date_of_birth",
            field=pgcrypto.fields.DatePGPPublicKeyField(
                null=True, verbose_name="date of birth"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_email",
            field=pgcrypto.fields.EmailPGPPublicKeyField(
                null=True, blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_first_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True, blank=True, max_length=30, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_id",
            field=apartment_application_service.fields.UUIDPGPPublicKeyField(
                null=True,
                editable=False,
                verbose_name="user identifier",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_last_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True, blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_phone_number",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True, max_length=40, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_postal_code",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True, max_length=10, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encrypted_street_address",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                null=True, max_length=200, verbose_name="street address"
            ),
        ),
        migrations.RunPython(copy_values),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_city",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=50, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_contact_language",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=2,
                verbose_name="contact language",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_date_of_birth",
            field=pgcrypto.fields.DatePGPPublicKeyField(verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_email",
            field=pgcrypto.fields.EmailPGPPublicKeyField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_first_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=30, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_id",
            field=apartment_application_service.fields.UUIDPGPPublicKeyField(
                editable=False, verbose_name="user identifier"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_last_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_phone_number",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=40, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_postal_code",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=10, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_street_address",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=200, verbose_name="street address"
            ),
        ),
    ]
