# Generated by Django 2.2.24 on 2021-06-17 11:04

import uuid

from django.db import migrations

import apartment_application_service.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_encrypted_profile_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="contact_language",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="street_address",
        ),
        migrations.AlterField(
            model_name="profile",
            name="encrypted_id",
            field=apartment_application_service.fields.UUIDPGPPublicKeyField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="user identifier",
            ),
        ),
    ]
