# Generated by Django 2.2.24 on 2021-06-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_unencrypted_profile_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_contact_language",
            new_name="contact_language",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_date_of_birth",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_first_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_last_name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_phone_number",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_postal_code",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_street_address",
            new_name="street_address",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="encrypted_id",
            new_name="id",
        ),
    ]
