# Generated by Django 2.2.24 on 2021-08-18 09:34

import uuid
from django.db import migrations, models

import apartment_application_service.fields


def migrate_profile_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.using(db_alias).all():
        profile.tmp_id = profile.pk
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_encrypted_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tmp_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="user identifier",
            ),
        ),
        migrations.RunPython(migrate_profile_id),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=apartment_application_service.fields.UUIDPGPPublicKeyField(
                default=uuid.uuid4,
                editable=False,
                verbose_name="user identifier",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tmp_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="user identifier",
            ),
        ),
        migrations.RemoveField(model_name="profile", name="id"),
        migrations.RenameField(model_name="profile", old_name="tmp_id", new_name="id"),
    ]
