# Generated by Django 3.2.6 on 2021-11-19 12:58

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calling_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=50, verbose_name="calling name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=30, verbose_name="middle name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="national_identification_number",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=11, verbose_name="national identification number"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number_nightly",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=50, verbose_name="phone number nightly"
            ),
        ),
    ]
