# Generated by Django 3.2.6 on 2021-11-30 10:16

import pgcrypto.fields
from django.db import migrations


def forwards_func(apps, schema_editor):
    profile = apps.get_model("users", "Profile")
    profile.objects.update(
        middle_name=None,
        calling_name=None,
        phone_number_nightly=None,
        national_identification_number=None,
    )


def reverse_func(apps, schema_editor):
    profile = apps.get_model("users", "Profile")
    profile.objects.update(
        middle_name="",
        calling_name="",
        phone_number_nightly="",
        national_identification_number="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_add_new_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="calling_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=50, null=True, verbose_name="calling name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=30, null=True, verbose_name="middle name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="national_identification_number",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="national identification number",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number_nightly",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="phone number nightly",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
