# Generated by Django 3.2.15 on 2024-08-18 06:28

import pgcrypto.fields
from django.db import migrations, models

from apartment_application_service.utils import decrypt_factory

field_names = (
    "calling_name",
    "city",
    "contact_language",
    "email",
    "first_name",
    "last_name",
    "middle_name",
    "phone_number_nightly",
    "phone_number",
    "postal_code",
    "street_address",
)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_djangouser_drupaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calling_name_plain",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="calling name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city_plain",
            field=models.CharField(max_length=50, null=True, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_language_plain",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=2,
                null=True,
                verbose_name="contact language",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_plain",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name_plain",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name_plain",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name_plain",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="middle name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number_nightly_plain",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="phone number nightly",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number_plain",
            field=models.CharField(
                max_length=40, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code_plain",
            field=models.CharField(
                max_length=10, null=True, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="street_address_plain",
            field=models.CharField(
                max_length=200, null=True, verbose_name="street address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=50, null=True, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_language",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=2,
                null=True,
                verbose_name="contact language",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=40, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="postal_code",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=10, null=True, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street_address",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=200, null=True, verbose_name="street address"
            ),
        ),
        migrations.RunPython(*decrypt_factory([("users", "Profile", field_names)])),
        migrations.RemoveField(
            model_name="profile",
            name="calling_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="contact_language",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number_nightly",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="street_address",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="calling_name_plain",
            new_name="calling_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="city_plain",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="contact_language_plain",
            new_name="contact_language",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="email_plain",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="first_name_plain",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="last_name_plain",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="middle_name_plain",
            new_name="middle_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="phone_number_plain",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="phone_number_nightly_plain",
            new_name="phone_number_nightly",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="postal_code_plain",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="street_address_plain",
            new_name="street_address",
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="", max_length=50, verbose_name="city"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_language",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                default="fi",
                max_length=2,
                verbose_name="contact language",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(
                blank=True, default="", max_length=254, verbose_name="email address"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="first name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="last name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                default="0", max_length=40, verbose_name="phone number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(
                default="0", max_length=10, verbose_name="postal code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="street_address",
            field=models.CharField(
                default="-", max_length=200, verbose_name="street address"
            ),
            preserve_default=False,
        ),
    ]
