# Generated by Django 4.2.7 on 2025-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_userkeyvalue"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userkeyvalue",
            constraint=models.UniqueConstraint(
                fields=("key", "value"), name="unique key-value pairs"
            ),
        ),
    ]
