# Generated by Django 4.2.7 on 2025-04-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_userkeyvalue_unique_key_value_pairs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userkeyvalue",
            name="unique key-value pairs",
        ),
        migrations.AddConstraint(
            model_name="userkeyvalue",
            constraint=models.UniqueConstraint(
                fields=("user", "key", "value"), name="unique key-value pairs"
            ),
        ),
    ]
