# Generated by Django 2.2.16 on 2021-03-25 08:30

import apartment.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', enumfields.fields.EnumField(enum=apartment.enums.IdentifierScheme, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.ManyToManyField(to='apartment.Identifier')),
            ],
        ),
        migrations.AddField(
            model_name='identifier',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.IdentifierScheme'),
        ),
        migrations.CreateModel(
            name='HistoricalApartment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apartment.Project')),
            ],
            options={
                'verbose_name': 'historical apartment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('identifiers', models.ManyToManyField(to='apartment.Identifier')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='identifier',
            unique_together={('scheme', 'identifier')},
        ),
    ]
