# Generated by Django 2.2.21 on 2021-05-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="apartment.Project",
            ),
        ),
    ]
