# Generated by Django 2.2.21 on 2021-06-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0013_alter_application_model"),
        ("apartment", "0002_auto_20210526_1910"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalapartment",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalapartment",
            name="project",
        ),
        migrations.AlterUniqueTogether(
            name="identifier",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="identifier",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="project",
            name="identifiers",
        ),
        migrations.DeleteModel(
            name="Apartment",
        ),
        migrations.DeleteModel(
            name="HistoricalApartment",
        ),
        migrations.DeleteModel(
            name="Identifier",
        ),
        migrations.DeleteModel(
            name="IdentifierSchema",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
