# Generated by Django 2.2.21 on 2021-06-03 12:57

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import apartment.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apartment", "0003_remove_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(max_length=200, verbose_name="street address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(max_length=200, verbose_name="street address"),
                ),
                (
                    "apartment_number",
                    models.PositiveSmallIntegerField(verbose_name="apartment number"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="apartment.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_type",
                    enumfields.fields.EnumField(
                        enum=apartment.enums.IdentifierSchemaType,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("identifier", models.CharField(max_length=36)),
                (
                    "apartment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="apartment.Apartment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="apartment.Project",
                    ),
                ),
            ],
            options={
                "unique_together": {("schema_type", "identifier")},
            },
        ),
    ]
