# Generated by Django 2.2.24 on 2021-08-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0006_alter_apartment_number_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="room_count",
            field=models.PositiveIntegerField(default=0, verbose_name="room count"),
            preserve_default=False,
        ),
    ]
