# Generated by Django 3.2.6 on 2021-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0009_project_ownership_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
