# Generated by Django 3.2.6 on 2022-01-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0010_bigauto_pk_field"),
        ("application_form", "0043_remove_apartmentreservation_apartment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="identifier",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="identifier",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="identifier",
            name="project",
        ),
        migrations.DeleteModel(
            name="Apartment",
        ),
        migrations.DeleteModel(
            name="Identifier",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
