default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: migrations|snapshots
