# Generated by Django 3.2.6 on 2021-11-19 12:58

import pgcrypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_add_new_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_information",
                    pgcrypto.fields.TextPGPPublicKeyField(
                        blank=True, verbose_name="additional information"
                    ),
                ),
                (
                    "last_contact_date",
                    pgcrypto.fields.DatePGPPublicKeyField(
                        blank=True, null=True, verbose_name="last contact date"
                    ),
                ),
                ("profiles", models.ManyToManyField(to="users.Profile")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
