# Generated by Django 2.2.16 on 2021-03-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hel_profile_uuid",
                    models.UUIDField(verbose_name="helsinki profile uuid"),
                ),
                (
                    "drupal_customer_id",
                    models.IntegerField(verbose_name="drupal customer id"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, verbose_name="email"),
                ),
                ("authorized", models.BooleanField(verbose_name="authorized")),
            ],
        ),
    ]
