# Generated by Django 3.2.12 on 2022-02-15 06:15

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_add_customer_primary_and_secondary_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="has_children",
            field=pgcrypto.fields.BooleanPGPPublicKeyField(
                blank=True, null=True, verbose_name="has children"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_hitas_ownership",
            field=pgcrypto.fields.BooleanPGPPublicKeyField(
                blank=True, null=True, verbose_name="has hitas ownership"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_age_over_55",
            field=pgcrypto.fields.BooleanPGPPublicKeyField(
                blank=True, null=True, verbose_name="is age over 55"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_right_of_occupancy_housing_changer",
            field=pgcrypto.fields.BooleanPGPPublicKeyField(
                blank=True,
                null=True,
                verbose_name="is right-of-occupancy housing changer",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="right_of_residence",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                blank=True, null=True, verbose_name="right of residence number"
            ),
        ),
    ]
