# Generated by Django 3.2.15 on 2023-09-24 15:58

from django.db import migrations

import apartment_application_service.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_add_customer_additional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="has_hitas_ownership",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                blank=True, null=True, verbose_name="has HITAS ownership"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_right_of_occupancy_housing_changer",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                blank=True,
                null=True,
                verbose_name="is right-of-occupancy housing changer",
            ),
        ),
    ]
