# Generated by Django 3.2.15 on 2023-09-24 22:05

from django.db import migrations

import apartment_application_service.fields


def populate_right_of_residence_is_old_batch(apps, schema_editor):
    Customer = apps.get_model("customer", "Customer")

    Customer.objects.exclude(right_of_residence=None).update(
        right_of_residence_is_old_batch=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_combine_common_application_data_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="right_of_residence_is_old_batch",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                blank=True,
                help_text="Only used when `right_of_residence` is set. When in use the "
                "default value is `false`. Value `true` means the right of "
                "residence number is granted on 31.8.2023 or before.",
                null=True,
                verbose_name="right of residence is old batch",
            ),
        ),
        migrations.RunPython(
            populate_right_of_residence_is_old_batch, migrations.RunPython.noop
        ),
    ]
