# Generated by Django 3.2.15 on 2024-08-13 14:01

from django.db import migrations, models
from django.db.models import Model


def decrypt_and_update_generic(model: Model, fields):
    instances = model.objects.all()
    for instance in instances:
        for field in fields:
            setattr(instance, f"{field}_plain", getattr(instance, field))

    model.objects.bulk_update(
        instances,
        fields,
    )


def decrypt_and_update_models(apps, schema_editor):
    fields = (
        "has_hitas_ownership",
        "is_right_of_occupancy_housing_changer",
        "right_of_residence_is_old_batch",
        "right_of_residence",
    )

    decrypt_and_update_generic(apps.get_model("customer", "Customer"), fields)


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_add_right_of_residence_is_old_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="has_hitas_ownership_plain",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="has HITAS ownership"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_right_of_occupancy_housing_changer_plain",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="is right-of-occupancy housing changer",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="right_of_residence_is_old_batch_plain",
            field=models.BooleanField(
                blank=True,
                help_text="Only used when `right_of_residence` is set. When in use the default value is `false`. Value `true` means the right of residence number is granted on 31.8.2023 or before.",
                null=True,
                verbose_name="right of residence is old batch",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="right_of_residence_plain",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="right of residence number"
            ),
        ),
        migrations.RunPython(decrypt_and_update_models),
        migrations.RemoveField(
            model_name="customer",
            name="has_hitas_ownership",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_right_of_occupancy_housing_changer",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="right_of_residence",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="right_of_residence_is_old_batch",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="has_hitas_ownership_plain",
            new_name="has_hitas_ownership",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="is_right_of_occupancy_housing_changer_plain",
            new_name="is_right_of_occupancy_housing_changer",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="right_of_residence_plain",
            new_name="right_of_residence",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="right_of_residence_is_old_batch_plain",
            new_name="right_of_residence_is_old_batch",
        ),
    ]
