# Generated by Django 3.2.15 on 2024-08-18 05:19

import pgcrypto.fields
from django.db import migrations, models

from apartment_application_service.utils import decrypt_factory

field_names = (
    "additional_information",
    "has_children",
    "is_age_over_55",
    "last_contact_date",
)


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_decrypt_common_application_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="additional_information_plain",
            field=models.TextField(
                blank=True, null=True, verbose_name="additional information"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_children_plain",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="has children"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_age_over_55_plain",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="is age over 55"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_contact_date_plain",
            field=models.DateField(
                blank=True, null=True, verbose_name="last contact date"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="additional_information",
            field=pgcrypto.fields.TextPGPPublicKeyField(
                blank=True, null=True, verbose_name="additional information"
            ),
        ),
        migrations.RunPython(*decrypt_factory([("customer", "Customer", field_names)])),
        migrations.RemoveField(
            model_name="customer",
            name="additional_information",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="has_children",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_age_over_55",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_contact_date",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="additional_information_plain",
            new_name="additional_information",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="has_children_plain",
            new_name="has_children",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="is_age_over_55_plain",
            new_name="is_age_over_55",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="last_contact_date_plain",
            new_name="last_contact_date",
        ),
        migrations.AlterField(
            model_name="customer",
            name="additional_information",
            field=models.TextField(
                blank=True, default="", verbose_name="additional information"
            ),
            preserve_default=False,
        ),
    ]
