# Generated by Django 3.2.6 on 2021-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0002_bigauto_pk_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="message",
            field=models.JSONField(),
        ),
    ]
