# Generated by Django 3.2.15 on 2022-11-23 07:19
import json
import os
from datetime import date
from decimal import Decimal

from django.db import migrations, models


def add_entries(apps, schema_editor):
    # noinspection PyPep8Naming
    CostIndex = apps.get_model("cost_index", "CostIndex")
    with open(
        os.path.join(os.path.dirname(__file__), "data/0001_cost_index_entries.json"),
        "r",
    ) as f:
        entries = json.load(f)
    objs = [
        CostIndex(value=Decimal(entry[0]), valid_from=date(*entry[1]))
        for entry in entries
    ]
    CostIndex.objects.bulk_create(objs)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name="costindex",
            options={"ordering": ["-valid_from"]},
        ),
        migrations.AlterField(
            model_name="costindex",
            name="valid_from",
            field=models.DateField(unique=True),
        ),
        migrations.RunPython(add_entries, migrations.RunPython.noop),
    ]
