# Generated by Django 3.2.15 on 2022-12-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0067_fix_metadata_handler"),
        ("cost_index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentRevaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                (
                    "start_cost_index_value",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "start_right_of_occupancy_cost",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "alteration_work",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("end_date", models.DateField()),
                (
                    "end_cost_index_value",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "end_right_of_occupancy_cost",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "apartment_reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revaluation",
                        to="application_form.apartmentreservation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
