# Generated by Django 3.2.15 on 2023-01-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0067_fix_metadata_handler"),
        ("cost_index", "0002_apartmentrevaluation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentrevaluation",
            old_name="end_right_of_occupancy_cost",
            new_name="end_right_of_occupancy_payment",
        ),
        migrations.RenameField(
            model_name="apartmentrevaluation",
            old_name="start_right_of_occupancy_cost",
            new_name="start_right_of_occupancy_payment",
        ),
        migrations.AddField(
            model_name="apartmentrevaluation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="apartmentrevaluation",
            name="apartment_reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revaluation",
                to="application_form.apartmentreservation",
            ),
        ),
    ]
