# Generated by Django 3.2.15 on 2023-09-08 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsKoLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asko_id", models.IntegerField()),
                ("object_id_int", models.BigIntegerField(null=True)),
                ("object_id_uuid", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("object_type", "asko_id")},
                "index_together": {
                    ("object_type", "asko_id", "object_id_int"),
                    ("object_type", "asko_id", "object_id_uuid"),
                },
            },
        ),
    ]
