# Generated by Django 3.2.15 on 2023-09-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("asko_import", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsKoImportLogEntry",
            options={
                "ordering": ("created_at", "id"),
                "verbose_name": "AsKo Import Log Entry",
                "verbose_name_plural": "AsKo Import Log Entries",
            },
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message_template", models.CharField(max_length=1000)),
                ("message", models.TextField()),
                ("level", models.IntegerField(blank=True, null=True)),
                ("exception", models.TextField(blank=True)),
                ("asko_id", models.IntegerField(blank=True, null=True)),
                (
                    "asko_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="asko_import.askolink",
                        related_name="logs",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
