# Generated by Django 3.2.6 on 2022-01-25 14:11

from django.db import migrations, models
import django.db.models.deletion


def delete_existing_apartment_installments(apps, schema_editor):
    """Make sure there are no existing ApartmentInstallment instances which would cause
    this migration to fail."""
    ApartmentInstallment = apps.get_model("invoicing", "ApartmentInstallment")
    ApartmentInstallment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0043_remove_apartmentreservation_apartment"),
        ("invoicing", "0002_alter_installments_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentinstallment",
            name="apartment_uuid",
        ),
        migrations.RunPython(
            delete_existing_apartment_installments, migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="apartmentinstallment",
            name="apartment_reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apartment_installments",
                to="application_form.apartmentreservation",
                verbose_name="apartment reservation",
            ),
        ),
    ]
