# Generated by Django 3.2.11 on 2022-01-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0003_change_apartment_installments_relate_to_reservations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentinstallment",
            name="percentage_specifier",
        ),
        migrations.RemoveField(
            model_name="apartmentinstallment",
            name="unit",
        ),
        migrations.AddConstraint(
            model_name="apartmentinstallment",
            constraint=models.UniqueConstraint(
                fields=("apartment_reservation", "type"), name="unique_reservation_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectinstallmenttemplate",
            constraint=models.UniqueConstraint(
                fields=("project_uuid", "type"), name="unique_project_type"
            ),
        ),
    ]
