# Generated by Django 3.2.12 on 2022-03-10 10:02
from itertools import cycle
from typing import Union

from django.db import migrations, models


REFERENCE_NUMBER_PREFIX = "2825"


def generate_reference_number(identifier: Union[int, str]) -> str:
    actual = f"{REFERENCE_NUMBER_PREFIX}{identifier}"

    coefficients = (7, 3, 1)
    check_digit = (
        10 - sum(int(d) * c for d, c in zip(reversed(actual), cycle(coefficients))) % 10
    )

    return f"{actual}{check_digit}"


def populate_actual_reference_numbers(apps, schema_editor):
    ApartmentInstallment = apps.get_model("invoicing", "ApartmentInstallment")
    for installment in ApartmentInstallment.objects.all():
        installment.reference_number = generate_reference_number(installment.id)
        installment.save(update_fields=("reference_number",))


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0004_apartment_installments_always_euros"),
    ]

    operations = [
        migrations.RunPython(
            populate_actual_reference_numbers, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="apartmentinstallment",
            name="reference_number",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="reference number"
            ),
        ),
    ]
