# Generated by Django 3.2.12 on 2022-05-05 18:53

from django.db import migrations


forwards_sql = """
UPDATE invoicing_apartmentinstallment
SET type = 'RIGHT_OF_OCCUPANCY_PAYMENT'
WHERE type = 'RIGHT_OF_RESIDENCE_FEE';

UPDATE invoicing_projectinstallmenttemplate
SET type = 'RIGHT_OF_OCCUPANCY_PAYMENT'
WHERE type = 'RIGHT_OF_RESIDENCE_FEE';
"""

backwards_sql = """
UPDATE invoicing_apartmentinstallment
SET type = 'RIGHT_OF_RESIDENCE_FEE'
WHERE type = 'RIGHT_OF_OCCUPANCY_PAYMENT';

UPDATE invoicing_projectinstallmenttemplate
SET type = 'RIGHT_OF_RESIDENCE_FEE'
WHERE type = 'RIGHT_OF_OCCUPANCY_PAYMENT';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0005_change_reference_number_unique"),
    ]

    operations = [migrations.RunSQL(forwards_sql, backwards_sql)]
