# Generated by Django 3.2.12 on 2022-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0007_apartmentinstallment_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentinstallment",
            name="added_to_be_sent_to_sap_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="added to be sent to SAP at"
            ),
        ),
        migrations.AddField(
            model_name="apartmentinstallment",
            name="sent_to_sap_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="sent to SAP at"
            ),
        ),
    ]
