# Generated by Django 3.2.13 on 2022-06-22 12:41

from django.db import migrations


forwards_sql = """
UPDATE invoicing_projectinstallmenttemplate
SET percentage_specifier = 'SALES_PRICE_FLEXIBLE'
WHERE percentage_specifier = 'DEBT_FREE_SALES_PRICE_FLEXIBLE';
"""

backwards_sql = """
UPDATE invoicing_projectinstallmenttemplate
SET percentage_specifier = 'DEBT_FREE_SALES_PRICE_FLEXIBLE'
WHERE percentage_specifier = 'SALES_PRICE_FLEXIBLE';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0008_add_sap_status_fields"),
    ]

    operations = [migrations.RunSQL(forwards_sql, backwards_sql)]
