# Generated by Django 3.2.14 on 2022-08-05 07:24

from django.db import migrations


def fix_handler(apps, schema_editor):
    ApartmentInstallment = apps.get_model("invoicing", "ApartmentInstallment")
    ApartmentInstallment.objects.update(handler="")


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0010_apartmentinstallment_handler"),
    ]

    operations = [
        migrations.RunPython(fix_handler, migrations.RunPython.noop),
    ]
