# Generated by Django 3.2.14 on 2022-08-12 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0011_fix_metadata_handler"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentinstallment",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="updated at",
            ),
        ),
        migrations.AddField(
            model_name="projectinstallmenttemplate",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="updated at",
            ),
        ),
    ]
