# Generated by Django 3.2.15 on 2023-01-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0013_add_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Payment batch"
                    ),
                ),
            ],
            options={
                "verbose_name": "payment batch",
                "verbose_name_plural": "payment batches",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="invoicing.paymentbatch",
                verbose_name="batch",
            ),
        ),
    ]
