# Generated by Django 3.2.15 on 2024-08-13 19:39

import pgcrypto.fields
from django.db import migrations, models

from apartment_application_service.utils import decrypt_factory

decrypt_fields = ("handler_plain",)


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0015_alter_apartmentinstallment_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentinstallment",
            name="handler_plain",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="handler"
            ),
        ),
        migrations.AlterField(
            model_name="apartmentinstallment",
            name="handler",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True,
                max_length=200,
                verbose_name="handler",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            *decrypt_factory([("invoicing", "ApartmentInstallment", ["handler"])])
        ),
        migrations.RemoveField(
            model_name="apartmentinstallment",
            name="handler",
        ),
        migrations.RenameField(
            model_name="apartmentinstallment",
            old_name="handler_plain",
            new_name="handler",
        ),
        migrations.AlterField(
            model_name="apartmentinstallment",
            name="handler",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="handler"
            ),
            preserve_default=False,
        ),
    ]
