# Generated by Django 3.2.15 on 2026-09-04 11:40

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0016_decrypt_apartmentinstallment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrupalPaymentSyncOutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application_id", models.IntegerField(verbose_name="application id")),
                ("reservation_id", models.IntegerField(verbose_name="reservation id")),
                ("project_uuid", models.UUIDField(verbose_name="project UUID")),
                (
                    "installment_type",
                    models.CharField(max_length=64, verbose_name="installment type"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="amount"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=255, verbose_name="account number"),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=64, verbose_name="reference number"),
                ),
                (
                    "sent_to_sap_at",
                    models.DateTimeField(verbose_name="sent to SAP at"),
                ),
                (
                    "source_event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="source event id",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="idempotency key",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="payload")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("failed", "failed"),
                            ("sent", "sent"),
                            ("dead_letter", "dead letter"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="attempts")),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="next retry at",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="last error code",
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, verbose_name="last error message"),
                ),
                (
                    "apartment_installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drupal_payment_sync_events",
                        to="invoicing.apartmentinstallment",
                        verbose_name="apartment installment",
                    ),
                ),
            ],
            options={
                "verbose_name": "drupal payment sync outbox event",
                "verbose_name_plural": "drupal payment sync outbox events",
                "ordering": ("id",),
            },
        ),
    ]
