#!/bin/bash

NOW="$(date +'%Y-%m-%d %T')"
APARTMENT_DATA_TRANSFER_PATH_ENV="${APARTMENT_DATA_TRANSFER_PATH:-transfer_files}"
CLEAN_APPS_DAYS_ENV="${CLEAN_APPS_DAYS:-7}"
dry_run=false

usage() {
  echo "Usage: This script deletes temp files generated by django apps from provided folder older then provided days."
  echo "       If apartment data transfer path arg not provided then env variable is APARTMENT_DATA_TRANSFER_PATH or default. Currently using '$APARTMENT_DATA_TRANSFER_PATH_ENV'."
  echo "       If clean apps days arg not provided then env variable is CLEAN_APPS_DAYS or default. Currently using '$CLEAN_APPS_DAYS_ENV'."
  echo "       To dry run provide -x option"
  echo "Examples:"
  echo " $0 [-p 'apartment data transfer path'] [-d 'days']"
  echo " $0 -x"
}

while getopts ":p:d:x" opt; do
  case $opt in
    p) APARTMENT_DATA_TRANSFER_PATH_ARG="$OPTARG"
    ;;
    d) CLEAN_APPS_DAYS_ARG="$OPTARG"
    ;;
    x) dry_run=true
    ;;
    \?) echo "Error: Invalid option -$OPTARG."
    usage
    exit 1
    ;;
    :) echo "Error: -${OPTARG} requires an argument."
    usage
    exit 1
    ;;
    *) usage
    exit 0
    ;;
  esac
done

if "$dry_run"; then
  echo "THIS IS DRY RUN!"
fi

if [[ -z $CLEAN_APPS_DAYS_ARG ]]; then
    echo "$NOW $0 INFO: Setting days from env variable CLEAN_APPS_DAYS or default ($CLEAN_APPS_DAYS_ENV)"
    CLEAN_APPS_DAYS_ARG=$CLEAN_APPS_DAYS_ENV
fi

if [[ -z $APARTMENT_DATA_TRANSFER_PATH_ARG ]]; then
    echo "$NOW $0 INFO: Setting apartment data path from env variable APARTMENT_DATA_TRANSFER_PATH or default ($APARTMENT_DATA_TRANSFER_PATH_ENV)"
    APARTMENT_DATA_TRANSFER_PATH_ARG=$APARTMENT_DATA_TRANSFER_PATH_ENV
fi

if [ ! -d $APARTMENT_DATA_TRANSFER_PATH_ARG ]; then
    echo "$NOW $0 WARNING: Folder '$APARTMENT_DATA_TRANSFER_PATH_ARG' does not exist. Skipping cleaning."
else
  echo "$NOW $0 INFO: Deleting files from '$APARTMENT_DATA_TRANSFER_PATH_ARG'..."
  if "$dry_run"; then
      find $APARTMENT_DATA_TRANSFER_PATH_ARG -maxdepth 1 -name "*.xml" -mtime +$CLEAN_APPS_DAYS_ARG -type f -print
  else
      find $APARTMENT_DATA_TRANSFER_PATH_ARG -maxdepth 1 -name "*.xml" -mtime +$CLEAN_APPS_DAYS_ARG -type f -print -delete
  fi
fi
