# Generated by Django 2.2.13 on 2020-10-12 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HasoApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "running_number",
                    models.CharField(max_length=255, verbose_name="running number"),
                ),
                (
                    "current_housing",
                    models.CharField(
                        choices=[
                            ("Omistusasunto", "Omistusasunto"),
                            ("Vuokra-asunto", "Vuokra-asunto"),
                            ("Asumisoikeusasunto", "Asumisoikeusasunto"),
                            ("Muu", "Muu"),
                        ],
                        max_length=255,
                        verbose_name="current housing",
                    ),
                ),
                (
                    "housing_description",
                    models.TextField(verbose_name="housing description"),
                ),
                (
                    "housing_type",
                    models.CharField(max_length=255, verbose_name="housing type"),
                ),
                ("housing_area", models.FloatField(verbose_name="housing area")),
                (
                    "is_changing_occupancy_apartment",
                    models.BooleanField(
                        default=False, verbose_name="is changing occupancy apartment"
                    ),
                ),
                (
                    "is_over_55",
                    models.BooleanField(default=False, verbose_name="is over 55"),
                ),
                ("project_uuid", models.UUIDField(verbose_name="project uuid")),
                (
                    "apartment_uuids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        size=None,
                        verbose_name="apartment uuids",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("add", "Can add new applications."),
                    ("change", "Can change the existing applications."),
                    ("delete", "Can remove remove the existing applications."),
                ],
            },
        ),
        migrations.CreateModel(
            name="HitasApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_previous_hitas_apartment",
                    models.BooleanField(
                        default=False, verbose_name="has previous hitas apartment"
                    ),
                ),
                (
                    "previous_hitas_description",
                    models.TextField(verbose_name="previous hitas descripiton"),
                ),
                (
                    "has_children",
                    models.BooleanField(default=False, verbose_name="has children"),
                ),
                ("project_uuid", models.UUIDField(verbose_name="project uuid")),
                ("apartment_uuid", models.UUIDField(verbose_name="apartment uuid")),
            ],
            options={
                "permissions": [
                    ("add", "Can add new applications."),
                    ("change", "Can change the existing applications."),
                    ("delete", "Can remove remove the existing applications."),
                ],
            },
        ),
    ]
