# Generated by Django 2.2.13 on 2020-10-21 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0003_add_application_mixin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "apartment_uuid",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="apartment uuid"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hasoapplication",
            name="apartment_uuids",
        ),
        migrations.RemoveField(
            model_name="hasoapplication",
            name="project_uuid",
        ),
        migrations.RemoveField(
            model_name="hitasapplication",
            name="apartment_uuid",
        ),
        migrations.RemoveField(
            model_name="hitasapplication",
            name="project_uuid",
        ),
        migrations.CreateModel(
            name="HasoApartmentPriority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "priority_number",
                    models.IntegerField(verbose_name="priority number"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haso_apartment_priorities",
                        to="application_form.Apartment",
                    ),
                ),
                (
                    "haso_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haso_apartment_priorities",
                        to="application_form.HasoApplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hitasapplication",
            name="apartment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hitas_applications",
                to="application_form.Apartment",
            ),
            preserve_default=False,
        ),
    ]
