# Generated by Django 2.2.16 on 2020-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0004_add_apartment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hasoapartmentpriority",
            options={
                "permissions": [
                    ("haso_create", "Can create new haso applications."),
                    ("haso_update", "Can update the existing haso applications."),
                    (
                        "haso_delete",
                        "Can remove remove the existing haso applications.",
                    ),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="hasoapplication",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hitasapplication",
            options={
                "permissions": [
                    ("hitas_create", "Can create new hitas applications."),
                    ("hitas_update", "Can update the existing hitas applications."),
                    (
                        "hitas_delete",
                        "Can remove remove the existing hitas applications.",
                    ),
                ]
            },
        ),
        migrations.AlterField(
            model_name="hasoapplication",
            name="right_of_occupancy_id",
            field=models.IntegerField(verbose_name="right of occupancy ID"),
        ),
    ]
