# Generated by Django 2.2.16 on 2020-11-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0006_hitasapplication_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="hasoapplication",
            name="applicant_token",
            field=models.CharField(
                default="",
                help_text="a token that can be associated with the applicant's user information.",
                max_length=200,
                verbose_name="applicant token",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hitasapplication",
            name="applicant_token",
            field=models.CharField(
                default="",
                help_text="a token that can be associated with the applicant's user information.",
                max_length=200,
                verbose_name="applicant token",
            ),
            preserve_default=False,
        ),
    ]
