# Generated by Django 2.2.16 on 2020-11-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("application_form", "0007_add_applicant_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalHitasApplication",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="is accepted"),
                ),
                (
                    "is_rejected",
                    models.BooleanField(default=False, verbose_name="is rejected"),
                ),
                (
                    "rejection_description",
                    models.TextField(default="", verbose_name="rejection description"),
                ),
                (
                    "applicant_has_accepted_offer",
                    models.BooleanField(
                        default=False, verbose_name="applicant has accepted offer"
                    ),
                ),
                (
                    "applicant_token",
                    models.CharField(
                        help_text="a token that can be associated with the applicant's user information.",
                        max_length=200,
                        verbose_name="applicant token",
                    ),
                ),
                (
                    "has_previous_hitas_apartment",
                    models.BooleanField(
                        default=False, verbose_name="has previous hitas apartment"
                    ),
                ),
                (
                    "previous_hitas_description",
                    models.TextField(verbose_name="previous hitas descripiton"),
                ),
                (
                    "has_children",
                    models.BooleanField(default=False, verbose_name="has children"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="application_form.Apartment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical hitas application",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHasoApplication",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="is accepted"),
                ),
                (
                    "is_rejected",
                    models.BooleanField(default=False, verbose_name="is rejected"),
                ),
                (
                    "rejection_description",
                    models.TextField(default="", verbose_name="rejection description"),
                ),
                (
                    "applicant_has_accepted_offer",
                    models.BooleanField(
                        default=False, verbose_name="applicant has accepted offer"
                    ),
                ),
                (
                    "applicant_token",
                    models.CharField(
                        help_text="a token that can be associated with the applicant's user information.",
                        max_length=200,
                        verbose_name="applicant token",
                    ),
                ),
                (
                    "right_of_occupancy_id",
                    models.IntegerField(verbose_name="right of occupancy ID"),
                ),
                (
                    "current_housing",
                    models.CharField(
                        choices=[
                            ("Omistusasunto", "Omistusasunto"),
                            ("Vuokra-asunto", "Vuokra-asunto"),
                            ("Asumisoikeusasunto", "Asumisoikeusasunto"),
                            ("Muu", "Muu"),
                        ],
                        max_length=255,
                        verbose_name="current housing",
                    ),
                ),
                (
                    "housing_description",
                    models.TextField(verbose_name="housing description"),
                ),
                (
                    "housing_type",
                    models.CharField(max_length=255, verbose_name="housing type"),
                ),
                ("housing_area", models.FloatField(verbose_name="housing area")),
                (
                    "is_changing_occupancy_apartment",
                    models.BooleanField(
                        default=False, verbose_name="is changing occupancy apartment"
                    ),
                ),
                (
                    "is_over_55",
                    models.BooleanField(
                        default=False, verbose_name="is applicant over 55 years old"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical haso application",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHasoApartmentPriority",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "priority_number",
                    models.IntegerField(verbose_name="priority number"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="application_form.Apartment",
                    ),
                ),
                (
                    "haso_application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="application_form.HasoApplication",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical haso apartment priority",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApartment",
            fields=[
                (
                    "apartment_uuid",
                    models.UUIDField(db_index=True, verbose_name="apartment uuid"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical apartment",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
