# Generated by Django 2.2.16 on 2020-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0008_historical_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasoapplication",
            name="rejection_description",
            field=models.TextField(
                blank=True, default="", verbose_name="rejection description"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhasoapplication",
            name="rejection_description",
            field=models.TextField(
                blank=True, default="", verbose_name="rejection description"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhitasapplication",
            name="rejection_description",
            field=models.TextField(
                blank=True, default="", verbose_name="rejection description"
            ),
        ),
        migrations.AlterField(
            model_name="hitasapplication",
            name="rejection_description",
            field=models.TextField(
                blank=True, default="", verbose_name="rejection description"
            ),
        ),
    ]
