# Generated by Django 2.2.21 on 2021-05-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0009_blank_rejection_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hasoapartmentpriority",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="hasoapartmentpriority",
            name="haso_application",
        ),
        migrations.RemoveField(
            model_name="historicalapartment",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalhasoapartmentpriority",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="historicalhasoapartmentpriority",
            name="haso_application",
        ),
        migrations.RemoveField(
            model_name="historicalhasoapartmentpriority",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalhasoapplication",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalhitasapplication",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="historicalhitasapplication",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="hitasapplication",
            name="apartment",
        ),
        migrations.DeleteModel(
            name="Apartment",
        ),
        migrations.DeleteModel(
            name="HasoApartmentPriority",
        ),
        migrations.DeleteModel(
            name="HasoApplication",
        ),
        migrations.DeleteModel(
            name="HistoricalApartment",
        ),
        migrations.DeleteModel(
            name="HistoricalHasoApartmentPriority",
        ),
        migrations.DeleteModel(
            name="HistoricalHasoApplication",
        ),
        migrations.DeleteModel(
            name="HistoricalHitasApplication",
        ),
        migrations.DeleteModel(
            name="HitasApplication",
        ),
    ]
