# Generated by Django 2.2.16 on 2021-03-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0009_blank_rejection_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalapartment",
            name="history_user",
        ),
        migrations.AlterField(
            model_name="hasoapartmentpriority",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="haso_apartment_priorities",
                to="apartment.Apartment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhasoapartmentpriority",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apartment.Apartment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhitasapplication",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apartment.Apartment",
            ),
        ),
        migrations.AlterField(
            model_name="hitasapplication",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hitas_applications",
                to="apartment.Apartment",
            ),
        ),
        migrations.DeleteModel(
            name="Apartment",
        ),
        migrations.DeleteModel(
            name="HistoricalApartment",
        ),
    ]
