# Generated by Django 2.2.16 on 2021-03-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0009_blank_rejection_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalapartment",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="hasoapartmentpriority",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="historicalhasoapartmentpriority",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="historicalhitasapplication",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="hitasapplication",
            name="apartment",
        ),
        migrations.DeleteModel(
            name="Apartment",
        ),
        migrations.DeleteModel(
            name="HistoricalApartment",
        ),
    ]
