# Generated by Django 2.2.16 on 2021-03-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0001_initial"),
        ("application_form", "0010_delete_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="hasoapartmentpriority",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="haso_apartment_priorities",
                to="apartment.Apartment",
            ),
        ),
        migrations.AddField(
            model_name="historicalhasoapartmentpriority",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apartment.Apartment",
            ),
        ),
        migrations.AddField(
            model_name="historicalhitasapplication",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apartment.Apartment",
            ),
        ),
        migrations.AddField(
            model_name="hitasapplication",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hitas_applications",
                to="apartment.Apartment",
            ),
        ),
    ]
