# Generated by Django 2.2.21 on 2021-06-03 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0012_auto_20210527_1000"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="apartments",
        ),
        migrations.RemoveField(
            model_name="application",
            name="state",
        ),
        migrations.RemoveField(
            model_name="applicationapartment",
            name="apartment",
        ),
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
