# Generated by Django 2.2.21 on 2021-06-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0013_alter_application_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationapartment",
            name="application",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="application",
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.DeleteModel(
            name="ApplicationApartment",
        ),
    ]
