# Generated by Django 2.2.21 on 2021-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0016_add_fields_to_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="contact_language",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=2,
                null=True,
                verbose_name="contact language",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="right_of_residence",
            field=models.CharField(
                default=1, max_length=10, verbose_name="right of residence number"
            ),
            preserve_default=False,
        ),
    ]
