# Generated by Django 2.2.21 on 2021-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0018_move_field_has_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="apartments",
            field=models.ManyToManyField(
                blank=True,
                through="application_form.ApplicationApartment",
                to="apartment.Apartment",
            ),
        ),
    ]
