# Generated by Django 2.2.21 on 2021-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0019_alter_field_apartments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="right_of_residence",
            field=models.CharField(
                max_length=10, null=True, verbose_name="right of residence number"
            ),
        ),
    ]
