# Generated by Django 2.2.24 on 2021-06-15 09:00

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0020_right_of_residence_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.date(2021, 6, 15), verbose_name="date of birth"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicant",
            name="ssn_suffix",
            field=models.CharField(
                default="DUMMY",
                max_length=5,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="personal identity code suffix",
            ),
            preserve_default=False,
        ),
    ]
