# Generated by Django 2.2.24 on 2021-06-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0022_add_encrypted_application_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="age",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="city",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="contact_language",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="is_primary_applicant",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="ssn_suffix",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="street_address",
        ),
        migrations.RemoveField(
            model_name="application",
            name="applicants_count",
        ),
        migrations.RemoveField(
            model_name="application",
            name="external_uuid",
        ),
        migrations.RemoveField(
            model_name="application",
            name="has_children",
        ),
        migrations.RemoveField(
            model_name="application",
            name="right_of_residence",
        ),
        migrations.RemoveField(
            model_name="application",
            name="type",
        ),
        migrations.RemoveField(
            model_name="applicationapartment",
            name="priority_number",
        ),
    ]
