# Generated by Django 2.2.24 on 2021-06-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0023_remove_unencrypted_application_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_age",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_contact_language",
            new_name="contact_language",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_date_of_birth",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_first_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_is_primary_applicant",
            new_name="is_primary_applicant",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_last_name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_phone_number",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_postal_code",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_ssn_suffix",
            new_name="ssn_suffix",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="encrypted_street_address",
            new_name="street_address",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="encrypted_applicants_count",
            new_name="applicants_count",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="encrypted_external_uuid",
            new_name="external_uuid",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="encrypted_has_children",
            new_name="has_children",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="encrypted_right_of_residence",
            new_name="right_of_residence",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="encrypted_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="applicationapartment",
            old_name="encrypted_priority_number",
            new_name="priority_number",
        ),
    ]
