# Generated by Django 2.2.24 on 2021-08-19 11:38

import pgcrypto.fields
from django.db import migrations


def set_invalid_right_of_residence_values_to_none(apps, schema_editor):
    # Numbers that cannot be interpreted as integers are replaced with None
    db_alias = schema_editor.connection.alias
    Application = apps.get_model("application_form", "Application")
    for application in Application.objects.using(db_alias).all().iterator():
        try:
            if application.right_of_residence is not None:
                int(application.right_of_residence)
        except ValueError:
            application.right_of_residence = None
            application.save(update_fields=["right_of_residence"])


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0024_rename_encrypted_application_fields"),
    ]

    operations = [
        migrations.RunPython(
            set_invalid_right_of_residence_values_to_none,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="application",
            name="right_of_residence",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                null=True, verbose_name="right of residence number"
            ),
        ),
    ]
