# Generated by Django 2.2.24 on 2021-08-19 13:05

import enumfields.fields
from django.db import migrations

import application_form.enums


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0025_right_of_residence_integer"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="state",
            field=enumfields.fields.EnumField(
                default="submitted",
                enum=application_form.enums.ApplicationState,
                max_length=15,
                verbose_name="application state",
            ),
        ),
    ]
