# Generated by Django 2.2.24 on 2021-08-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0026_application_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.Profile",
            ),
        ),
    ]
