# Generated by Django 3.2.6 on 2021-12-22 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0030_bigauto_pk_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotteryeventresult",
            name="application_apartment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="application_form.applicationapartment",
            ),
        ),
    ]
