# Generated by Django 3.2.6 on 2021-12-22 08:02

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    application_apartment = apps.get_model("application_form", "ApplicationApartment")
    for item in application_apartment.objects.all():
        item.apartment_reservation.apartment = item.apartment
        item.apartment_reservation.save()


def reverse_func(apps, schema_editor):
    application_apartment = apps.get_model("application_form", "ApplicationApartment")
    apartment_queue = apps.get_model("application_form", "ApartmentQueue")
    for item in application_apartment.objects.all():
        queue = item.apartment.queue
        if not queue:
            queue = apartment_queue.objects.create(
                apartment=application_apartment.apartment
            )
        item.apartment_reservation.queue = queue
        item.apartment_reservation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0010_bigauto_pk_field"),
        ("application_form", "0031_alter_lotteryeventresult_application_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentqueueapplication",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_applications",
                to="apartment.apartment",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
        migrations.AlterUniqueTogether(
            name="apartmentqueueapplication",
            unique_together={("apartment", "application_apartment")},
        ),
        migrations.RemoveField(
            model_name="apartmentqueueapplication",
            name="queue",
        ),
        migrations.DeleteModel(
            name="ApartmentQueue",
        ),
    ]
