# Generated by Django 3.2.6 on 2021-12-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0010_bigauto_pk_field"),
        ("application_form", "0032_drop_apartment_queue"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApartmentQueueApplication",
            new_name="ApartmentReservation",
        ),
    ]
