# Generated by Django 3.2.6 on 2021-12-22 12:17

import enumfields.fields
from django.db import migrations

import application_form.enums


def forwards_func(apps, schema_editor):
    application_apartment = apps.get_model("application_form", "ApplicationApartment")
    for item in application_apartment.objects.all():
        item.apartment_reservation.state = (
            application_form.enums.ApartmentReservationState(item.state.value)
        )
        item.apartment_reservation.save()


def reverse_func(apps, schema_editor):
    apartment_reservation = apps.get_model("application_form", "ApartmentReservation")
    for item in apartment_reservation.objects.all():
        try:
            item.application_apartment.state = (
                application_form.enums.ApartmentReservationState(item.state.value)
            )
        except ValueError:
            item.application_apartment.state = (
                application_form.enums.ApartmentReservationState.SUBMITTED
            )
        item.application_apartment.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "application_form",
            "0033_rename_apartmentqueueapplication_apartmentreservation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="state",
            field=enumfields.fields.EnumField(
                default="submitted",
                enum=application_form.enums.ApartmentReservationState,
                max_length=15,
                verbose_name="apartment reservation state",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
    ]
