# Generated by Django 3.2.6 on 2021-12-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0034_move_reservation_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationapartment",
            name="state",
        ),
    ]
