# Generated by Django 3.2.6 on 2021-12-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0035_remove_applicationapartment_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentreservation",
            name="application_apartment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartment_reservation",
                to="application_form.applicationapartment",
            ),
        ),
    ]
