# Generated by Django 3.2.6 on 2021-12-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0010_bigauto_pk_field"),
        ("application_form", "0036_alter_apartmentreservation_application_apartment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentreservation",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="apartment.apartment",
            ),
        ),
    ]
