# Generated by Django 3.2.6 on 2022-01-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0010_bigauto_pk_field"),
        ("application_form", "0040_lotteryevent_apartment_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotteryevent",
            name="apartment",
        ),
    ]
