# Generated by Django 3.2.6 on 2022-01-17 12:48

import uuid

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    lottery_event = apps.get_model("application_form", "ApartmentReservation")
    for item in lottery_event.objects.all():
        item.aparment_uuid = item.apartment.uuid
        item.save(update_fields=["apartment_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0041_remove_lotteryevent_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="apartment_uuid",
            field=models.UUIDField(
                default=uuid.UUID(int=0), verbose_name="apartment uuid"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
