# Generated by Django 3.2.6 on 2022-01-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0042_apartmentreservation_apartment_uuid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apartmentreservation",
            unique_together={("apartment_uuid", "application_apartment")},
        ),
        migrations.RemoveField(
            model_name="apartmentreservation",
            name="apartment",
        ),
    ]
