# Generated by Django 3.2.11 on 2022-02-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0045_populate_application_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="profile",
        ),
        migrations.AlterField(
            model_name="application",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
    ]
