# Generated by Django 3.2.12 on 2022-03-01 20:25

from django.db import migrations
from django.db.models import F


def forwards(apps, schema_editor):
    ApartmentReservation = apps.get_model("application_form", "ApartmentReservation")
    LotteryEventResult = apps.get_model("application_form", "LotteryEventResult")

    ApartmentReservation.objects.update(queue_position=F("queue_position") + 1)
    LotteryEventResult.objects.update(result_position=F("result_position") + 1)


def backwards(apps, schema_editor):
    ApartmentReservation = apps.get_model("application_form", "ApartmentReservation")
    LotteryEventResult = apps.get_model("application_form", "LotteryEventResult")

    ApartmentReservation.objects.update(queue_position=F("queue_position") - 1)
    LotteryEventResult.objects.update(result_position=F("result_position") - 1)


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0046_remove_application_profile"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
