# Generated by Django 3.2.12 on 2022-03-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0047_make_queue_position_start_from_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentreservation",
            name="application_apartment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartment_reservation",
                to="application_form.applicationapartment",
            ),
        ),
    ]
