# Generated by Django 3.2.12 on 2022-03-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_add_customer_additional_fields"),
        ("application_form", "0048_alter_apartmentreservation_application_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
    ]
