# Generated by Django 3.2.12 on 2022-03-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_add_customer_additional_fields"),
        ("application_form", "0050_populate_apartment_reservation_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentreservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apartment_reservations",
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
    ]
