# Generated by Django 3.2.12 on 2022-03-28 11:13

import application_form.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("application_form", "0052_alter_apartmentreservation_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentReservationStateChangeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    enumfields.fields.EnumField(
                        enum=application_form.enums.ApartmentReservationState,
                        max_length=32,
                        verbose_name="apartment reservation state",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="comment"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_change_events",
                        to="application_form.apartmentreservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="apartmentqueuechangeevent",
            name="queue_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_change_events",
                to="application_form.apartmentreservation",
            ),
        ),
    ]
