# Generated by Django 3.2.12 on 2022-04-11 12:24

import enumfields.fields
from django.db import migrations

import application_form.enums


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0053_add_apartmentreservationstatechangeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservationstatechangeevent",
            name="cancellation_reason",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=application_form.enums.ApartmentReservationCancellationReason,
                max_length=32,
                null=True,
                verbose_name="cancellation reason",
            ),
        ),
    ]
