# Generated by Django 3.2.12 on 2022-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application_form",
            "0054_apartmentreservationstatechangeevent_cancellation_reason",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentreservation",
            name="queue_position",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="position in queue"
            ),
        ),
    ]
