# Generated by Django 3.2.12 on 2022-04-21 13:51

from django.db import migrations

import apartment_application_service.fields


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0055_alter_apartmentreservation_queue_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="has_hitas_ownership",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                blank=True, null=True, verbose_name="has HITAS ownership"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="is_right_of_occupancy_housing_changer",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                blank=True,
                null=True,
                verbose_name="is right of occupancy housing changer",
            ),
        ),
    ]
