# Generated by Django 3.2.12 on 2022-04-14 09:27

from django.db import migrations, models

from application_form.models import ApartmentReservation, LotteryEventResult


class Migration(migrations.Migration):
    def migrate_list_position(apps, schema_editor):
        apartment_uuids = ApartmentReservation.objects.values_list(
            "apartment_uuid", flat=True
        ).distinct("apartment_uuid")

        for apartment_uuid in apartment_uuids:
            for i, reservation in enumerate(
                ApartmentReservation.objects.filter(
                    apartment_uuid=apartment_uuid
                ).order_by(
                    "application_apartment__lotteryeventresult__result_position"
                ),
                1,
            ):
                reservation.list_position = i
                reservation.save(update_fields=["list_position"])

    dependencies = [
        ("application_form", "0056_add_fields_to_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="list_position",
            field=models.IntegerField(
                verbose_name="position in list", null=True, blank=True
            ),
        ),
        migrations.RunPython(
            migrate_list_position, reverse_code=migrations.RunPython.noop
        ),
    ]
