# Generated by Django 3.2.12 on 2022-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0061_add_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentreservation",
            name="apartment_uuid",
            field=models.UUIDField(db_index=True, verbose_name="apartment uuid"),
        ),
    ]
