# Generated by Django 3.2.13 on 2022-06-08 20:36

from django.db import migrations
import pgcrypto.fields


def populate_reservation_right_of_residence(apps, schema_editor):
    ApartmentReservation = apps.get_model("application_form", "ApartmentReservation")

    for reservation in ApartmentReservation.objects.all():
        if reservation.application_apartment:
            right_of_residence = (
                reservation.application_apartment.application.right_of_residence
            )
        else:
            right_of_residence = reservation.customer.right_of_residence

        ApartmentReservation.objects.filter(pk=reservation.pk).update(
            right_of_residence=right_of_residence
        )


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0062_alter_apartmentreservation_apartment_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="right_of_residence",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                blank=True, null=True, verbose_name="right of residence number"
            ),
        ),
        migrations.RunPython(
            populate_reservation_right_of_residence, migrations.RunPython.noop
        ),
    ]
