# Generated by Django 3.2.14 on 2022-08-05 08:22

from django.db import migrations
import pgcrypto.fields


def fix_handler(apps, schema_editor):
    ApartmentReservation = apps.get_model("application_form", "ApartmentReservation")
    LotteryEvent = apps.get_model("application_form", "LotteryEvent")
    Offer = apps.get_model("application_form", "Offer")

    ApartmentReservation.objects.update(handler="")
    LotteryEvent.objects.update(handler="")
    Offer.objects.update(handler="")


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0066_alter_metadata_fields"),
    ]

    operations = [
        migrations.RunPython(fix_handler, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="apartmentreservation",
            name="handler",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=200, verbose_name="handler"
            ),
        ),
        migrations.AlterField(
            model_name="lotteryevent",
            name="handler",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=200, verbose_name="handler"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="handler",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                blank=True, max_length=200, verbose_name="handler"
            ),
        ),
    ]
