# Generated by Django 3.2.15 on 2023-09-24 15:58

import pgcrypto.fields
from django.db import migrations

import apartment_application_service.fields


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0067_fix_metadata_handler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="is_right_of_occupancy_housing_changer",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                blank=True,
                null=True,
                verbose_name="is right-of-occupancy housing changer",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="right_of_residence",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                blank=True, null=True, verbose_name="right of residence number"
            ),
        ),
    ]
