# Generated by Django 3.2.15 on 2024-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0070_add_lotteryevent_apartment_uuid_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="submitted_late",
            field=models.BooleanField(default=False, verbose_name="submitted late"),
        ),
    ]
