# Generated by Django 3.2.15 on 2024-08-13 14:01

from django.db import migrations, models

from apartment_application_service.utils import decrypt_factory

decrypt_fields = (
    "has_hitas_ownership",
    "is_right_of_occupancy_housing_changer",
    "right_of_residence_is_old_batch",
    "right_of_residence",
)


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0071_apartmentreservation_submitted_late"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="has_hitas_ownership_plain",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="has HITAS ownership"
            ),
        ),
        migrations.AddField(
            model_name="apartmentreservation",
            name="is_right_of_occupancy_housing_changer_plain",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="is right-of-occupancy housing changer",
            ),
        ),
        migrations.AddField(
            model_name="apartmentreservation",
            name="right_of_residence_is_old_batch_plain",
            field=models.BooleanField(
                blank=True,
                help_text="Only used when `right_of_residence` is set. When in use the default value is `false`. Value `true` means the right of residence number is granted on 31.8.2023 or before.",
                null=True,
                verbose_name="right of residence is old batch",
            ),
        ),
        migrations.AddField(
            model_name="apartmentreservation",
            name="right_of_residence_plain",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="right of residence number"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="has_hitas_ownership_plain",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="has HITAS ownership"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="is_right_of_occupancy_housing_changer_plain",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="is right-of-occupancy housing changer",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="right_of_residence_is_old_batch_plain",
            field=models.BooleanField(
                blank=True,
                help_text="Only used when `right_of_residence` is set. When in use the default value is `false`. Value `true` means the right of residence number is granted on 31.8.2023 or before.",
                null=True,
                verbose_name="right of residence is old batch",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="right_of_residence_plain",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="right of residence number"
            ),
        ),
        migrations.RunPython(
            *decrypt_factory(
                [
                    ("application_form", "apartmentreservation", decrypt_fields),
                    ("application_form", "application", decrypt_fields),
                ]
            )
        ),
        migrations.RemoveField(
            model_name="apartmentreservation",
            name="has_hitas_ownership",
        ),
        migrations.RemoveField(
            model_name="apartmentreservation",
            name="is_right_of_occupancy_housing_changer",
        ),
        migrations.RemoveField(
            model_name="apartmentreservation",
            name="right_of_residence",
        ),
        migrations.RemoveField(
            model_name="apartmentreservation",
            name="right_of_residence_is_old_batch",
        ),
        migrations.RemoveField(
            model_name="application",
            name="has_hitas_ownership",
        ),
        migrations.RemoveField(
            model_name="application",
            name="is_right_of_occupancy_housing_changer",
        ),
        migrations.RemoveField(
            model_name="application",
            name="right_of_residence",
        ),
        migrations.RemoveField(
            model_name="application",
            name="right_of_residence_is_old_batch",
        ),
        migrations.RenameField(
            model_name="apartmentreservation",
            old_name="has_hitas_ownership_plain",
            new_name="has_hitas_ownership",
        ),
        migrations.RenameField(
            model_name="apartmentreservation",
            old_name="is_right_of_occupancy_housing_changer_plain",
            new_name="is_right_of_occupancy_housing_changer",
        ),
        migrations.RenameField(
            model_name="apartmentreservation",
            old_name="right_of_residence_plain",
            new_name="right_of_residence",
        ),
        migrations.RenameField(
            model_name="apartmentreservation",
            old_name="right_of_residence_is_old_batch_plain",
            new_name="right_of_residence_is_old_batch",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="has_hitas_ownership_plain",
            new_name="has_hitas_ownership",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="is_right_of_occupancy_housing_changer_plain",
            new_name="is_right_of_occupancy_housing_changer",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="right_of_residence_plain",
            new_name="right_of_residence",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="right_of_residence_is_old_batch_plain",
            new_name="right_of_residence_is_old_batch",
        ),
    ]
