# Generated by Django 3.2.15 on 2024-08-18 08:49
import uuid

import enumfields.fields
import pgcrypto.fields
from django.db import migrations, models

import apartment_application_service.fields
import application_form.enums
from apartment_application_service.utils import decrypt_factory

applicant_field_names = (
    "age",
    "city",
    "contact_language",
    "email",
    "first_name",
    "is_primary_applicant",
    "last_name",
    "phone_number",
    "postal_code",
    "street_address",
)
application_field_names = (
    "applicants_count",
    "external_uuid",
    "has_children",
    "sender_names",
    "type",
)

application_apartment_field_names = ("priority_number",)


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0072_decrypt_common_application_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="age_plain",
            field=models.IntegerField(null=True, verbose_name="age"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="city_plain",
            field=models.CharField(max_length=50, null=True, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="contact_language_plain",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                max_length=2,
                null=True,
                verbose_name="contact language",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="email_plain",
            field=models.EmailField(max_length=254, null=True, verbose_name="email"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="first_name_plain",
            field=models.CharField(max_length=30, null=True, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="is_primary_applicant_plain",
            field=models.BooleanField(null=True, verbose_name="is primary applicant"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="last_name_plain",
            field=models.CharField(max_length=150, null=True, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="phone_number_plain",
            field=models.CharField(
                max_length=40, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="postal_code_plain",
            field=models.CharField(
                max_length=10, null=True, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="street_address_plain",
            field=models.CharField(
                max_length=200, null=True, verbose_name="street address"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="applicants_count_plain",
            field=models.IntegerField(null=True, verbose_name="applicants count"),
        ),
        migrations.AddField(
            model_name="application",
            name="external_uuid_plain",
            field=models.UUIDField(
                editable=False, null=True, verbose_name="application identifier"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="has_children_plain",
            field=models.BooleanField(null=True, verbose_name="has children"),
        ),
        migrations.AddField(
            model_name="application",
            name="sender_names_plain",
            field=models.CharField(
                max_length=200, null=True, verbose_name="sender names"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="type_plain",
            field=enumfields.fields.EnumField(
                enum=application_form.enums.ApplicationType,
                max_length=15,
                null=True,
                verbose_name="application type",
            ),
        ),
        migrations.AddField(
            model_name="applicationapartment",
            name="priority_number_plain",
            field=models.IntegerField(null=True, verbose_name="priority number"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="age",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                null=True, verbose_name="age"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="city",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=50, null=True, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="email",
            field=pgcrypto.fields.EmailPGPPublicKeyField(
                max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="first_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=30, null=True, verbose_name="first name"
            ),
        ),
        # For fields with a default value, this needs to be done in two steps
        # so that django doesn't try to set the default on DB devel (which will fail
        # as the db field is not boolean but bytea).
        # 1/2 no default + NOT NULL
        migrations.AlterField(
            model_name="applicant",
            name="is_primary_applicant",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                verbose_name="is primary applicant"
            ),
        ),
        # 2/2 no default + NULL
        migrations.AlterField(
            model_name="applicant",
            name="is_primary_applicant",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                null=True, verbose_name="is primary applicant"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="last_name",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone_number",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=40, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="postal_code",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=10, null=True, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="street_address",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=200, null=True, verbose_name="street address"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="applicants_count",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                null=True, verbose_name="applicants count"
            ),
        ),
        # 1 / 2
        migrations.AlterField(
            model_name="application",
            name="external_uuid",
            field=apartment_application_service.fields.UUIDPGPPublicKeyField(
                editable=False, verbose_name="application identifier"
            ),
        ),
        # 2 / 2
        migrations.AlterField(
            model_name="application",
            name="external_uuid",
            field=apartment_application_service.fields.UUIDPGPPublicKeyField(
                editable=False, null=True, verbose_name="application identifier"
            ),
        ),
        # 1 / 2
        migrations.AlterField(
            model_name="application",
            name="has_children",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                verbose_name="has children"
            ),
        ),
        # 2 / 2
        migrations.AlterField(
            model_name="application",
            name="has_children",
            field=apartment_application_service.fields.BooleanPGPPublicKeyField(
                null=True, verbose_name="has children"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sender_names",
            field=pgcrypto.fields.CharPGPPublicKeyField(
                max_length=200, null=True, verbose_name="sender names"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="type",
            field=apartment_application_service.fields.EnumPGPPublicKeyField(
                enum=application_form.enums.ApplicationType,
                max_length=15,
                null=True,
                verbose_name="application type",
            ),
        ),
        migrations.AlterField(
            model_name="applicationapartment",
            name="priority_number",
            field=pgcrypto.fields.IntegerPGPPublicKeyField(
                null=True, verbose_name="priority number"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicationapartment",
            unique_together=set(),
        ),
        migrations.RunPython(
            *decrypt_factory(
                [
                    ("application_form", "Applicant", applicant_field_names),
                    ("application_form", "Application", application_field_names),
                    (
                        "application_form",
                        "ApplicationApartment",
                        application_apartment_field_names,
                    ),
                ]
            )
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="age",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="city",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="contact_language",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="is_primary_applicant",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="street_address",
        ),
        migrations.RemoveField(
            model_name="application",
            name="applicants_count",
        ),
        migrations.RemoveField(
            model_name="application",
            name="external_uuid",
        ),
        migrations.RemoveField(
            model_name="application",
            name="has_children",
        ),
        migrations.RemoveField(
            model_name="application",
            name="sender_names",
        ),
        migrations.RemoveField(
            model_name="application",
            name="type",
        ),
        migrations.RemoveField(
            model_name="applicationapartment",
            name="priority_number",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="age_plain",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="city_plain",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="contact_language_plain",
            new_name="contact_language",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="email_plain",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="first_name_plain",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="is_primary_applicant_plain",
            new_name="is_primary_applicant",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="last_name_plain",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="phone_number_plain",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="postal_code_plain",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="street_address_plain",
            new_name="street_address",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="applicants_count_plain",
            new_name="applicants_count",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="external_uuid_plain",
            new_name="external_uuid",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="has_children_plain",
            new_name="has_children",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="sender_names_plain",
            new_name="sender_names",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="type_plain",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="applicationapartment",
            old_name="priority_number_plain",
            new_name="priority_number",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="age",
            field=models.IntegerField(default=0, verbose_name="age"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="city",
            field=models.CharField(default="-", max_length=50, verbose_name="city"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="email",
            field=models.EmailField(
                default="missing@localhost", max_length=254, verbose_name="email"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="first_name",
            field=models.CharField(
                default="-", max_length=30, verbose_name="first name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="is_primary_applicant",
            field=models.BooleanField(
                default=False, verbose_name="is primary applicant"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="last_name",
            field=models.CharField(
                default="-", max_length=150, verbose_name="last name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone_number",
            field=models.CharField(
                default="-", max_length=40, verbose_name="phone number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="postal_code",
            field=models.CharField(
                default="-", max_length=10, verbose_name="postal code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="street_address",
            field=models.CharField(
                default="-", max_length=200, verbose_name="street address"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="applicants_count",
            field=models.IntegerField(default=0, verbose_name="applicants count"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="external_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                verbose_name="application identifier",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="has_children",
            field=models.BooleanField(default=False, verbose_name="has children"),
        ),
        migrations.AlterField(
            model_name="application",
            name="sender_names",
            field=models.CharField(
                default="-", max_length=200, verbose_name="sender names"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="type",
            field=enumfields.fields.EnumField(
                default=application_form.enums.ApplicationType.HITAS,
                enum=application_form.enums.ApplicationType,
                max_length=15,
                verbose_name="application type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationapartment",
            name="priority_number",
            field=models.IntegerField(default=0, verbose_name="priority number"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="applicationapartment",
            unique_together={("application", "priority_number")},
        ),
    ]
