# Generated by Django 4.2.7 on 2025-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_form", "0073_decrypt_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreservation",
            name="queue_position_before_cancelation",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="position in queue before cancelation",
            ),
        ),
    ]
