# Generated by Django 4.2.11 on 2026-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application_form",
            "0074_apartmentreservation_queue_position_before_cancelation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="drupal_application_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Drupal application node ID"
            ),
        ),
    ]
