# This is a basic workflow to help you get started with Actions

name: apartment-application-service CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SECRET_KEY: topsecret123
  DATABASE_URL: postgres://postgres:postgres@localhost/apartment-application

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9]
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apartment-application
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install codecov -r requirements.txt -r requirements-dev.txt

      - name: Check and run migrations
        run: |
          python manage.py makemigrations --dry-run --check
          python manage.py migrate

      - name: Run black, flake8 and isort
        run: |
          black --check .
          flake8
          isort . --check-only --diff

      # - name: Run tests
      #   run: |
      #     pytest -ra -vvv --doctest-modules --cov=.
      #     ./run-type-checks

      - name: Run codecov
        run: codecov
